// ============================================================================
// TRAINING SIMULATION SCENARIOS — Synthetic data + scenario definitions
// ============================================================================
// All data here is SYNTHETIC. No real prospects, customers, properties, or
// business records are referenced. The simulation never touches production
// entities or APIs. See simulationEngine.js for the reducer + validation.
// ============================================================================

export const SIMULATION_LEVELS = [
  { id: "WATCH_IT", label: "Watch It", description: "Observe the correct process step-by-step.", color: "#6B7280" },
  { id: "FOLLOW_IT", label: "Follow It", description: "Follow guided prompts through the workflow.", color: "#3B82F6" },
  { id: "DO_IT", label: "Do It", description: "Perform the workflow with minimal guidance.", color: "#B8956A" },
  { id: "SOLVE_IT", label: "Solve It", description: "Handle objections and edge cases.", color: "#F59E0B" },
  { id: "ONBOARD_IT", label: "Onboard It", description: "Guide a customer through onboarding.", color: "#8B5CF6" },
  { id: "TEACH_IT", label: "Teach It", description: "Explain the process back to demonstrate mastery.", color: "#EC4899" },
  { id: "PROVE_IT", label: "Prove It", description: "Final certification scenario.", color: "#EF4444" },
];

// --- Pricing (mirrors DEFAULT_PRICING_CONFIG from mediaPricingEngine.ts) ---
export const PRICING_TIERS = [
  { tier: "TIER_1", min: 0, max: 2500, label: "Up to 2,500 sqft", prices: { mls_walkthrough: 100, photo_essentials: 275, photo_cinematic: 475, premium_bundle: 675 } },
  { tier: "TIER_2", min: 2501, max: 3500, label: "2,501–3,500 sqft", prices: { mls_walkthrough: 125, photo_essentials: 325, photo_cinematic: 525, premium_bundle: 750 } },
  { tier: "TIER_3", min: 3501, max: 5000, label: "3,501–5,000 sqft", prices: { mls_walkthrough: 150, photo_essentials: 375, photo_cinematic: 575, premium_bundle: 825 } },
  { tier: "TIER_4", min: 5001, max: 7500, label: "5,001–7,500 sqft", prices: { mls_walkthrough: 200, photo_essentials: 450, photo_cinematic: 650, premium_bundle: 950 } },
  { tier: "TIER_5", min: 7501, max: 10000, label: "7,501–10,000 sqft", prices: { mls_walkthrough: 275, photo_essentials: 575, photo_cinematic: 775, premium_bundle: 1100 } },
  { tier: "CUSTOM", min: 10001, max: Infinity, label: "10,001+ sqft (Custom Quote)", prices: {} },
];

export const PACKAGES = [
  { id: "mls_walkthrough", name: "MLS Walkthrough", description: "Zillow-style 45-second walkthrough video" },
  { id: "photo_essentials", name: "Photo Essentials", description: "Professional photography package" },
  { id: "photo_cinematic", name: "Photo + Cinematic", description: "Photography + cinematic video" },
  { id: "premium_bundle", name: "Premium Bundle", description: "Full premium media package" },
];

export const ADD_ONS = [
  { id: "drone", name: "Drone add-on (photos + short clips)", price: 125 },
  { id: "3d_tour", name: "3D Tour", price: 125 },
  { id: "twilight", name: "Twilight exterior edits (up to 5 photos)", price: 125 },
  { id: "rush_delivery", name: "Next-day rush delivery (when available)", price: 100 },
  { id: "vertical_reel", name: "Additional vertical reel", price: 40 },
  { id: "ai_staging", name: "AI Staging", price: 125 },
];

export const PREFERRED_CONFIG = { monthly_price: 29.99, regular_discount_rate: 0.10, mls_flat_discount: 5.00 };

// --- Synthetic Data ---
export const SYNTHETIC_PROSPECTS = [
  { id: "sim_prospect_1", name: "Sarah Chen", role: "Real Estate Agent", brokerage: "Premier Realty Group", market: "Atlanta, GA", listing_address: "123 Oakwood Dr NE, Atlanta, GA 30305", listing_price: 450000, listing_sqft: 2200, has_professional_video: false, email: "s.chen@sim.example", phone: "(404) 555-0142" },
  { id: "sim_prospect_2", name: "Marcus Johnson", role: "Broker", brokerage: "Johnson & Associates", market: "Marietta, GA", listing_address: "456 Maple St, Marietta, GA 30060", listing_price: 625000, listing_sqft: 3100, has_professional_video: true, email: "m.johnson@sim.example", phone: "(770) 555-0198" },
  { id: "sim_prospect_3", name: "Priya Patel", role: "Real Estate Agent", brokerage: "Keller Williams Intown", market: "Decatur, GA", listing_address: "789 Sycamore Ln, Decatur, GA 30030", listing_price: 385000, listing_sqft: 1800, has_professional_video: false, email: "p.patel@sim.example", phone: "(404) 555-0177" },
  { id: "sim_prospect_4", name: "Coastal Builders LLC", role: "Builder", brokerage: "Coastal Builders", market: "Smyrna, GA", listing_address: "12 Riverbend Way, Smyrna, GA 30080", listing_price: 890000, listing_sqft: 4200, has_professional_video: false, email: "info@coastalbuilders.sim.example", phone: "(770) 555-0233" },
];

export const SYNTHETIC_PROPERTIES = [
  { id: "sim_prop_1", address: "123 Oakwood Dr NE, Atlanta, GA 30305", sqft: 2200, tier: "TIER_1" },
  { id: "sim_prop_2", address: "456 Maple St, Marietta, GA 30060", sqft: 3100, tier: "TIER_2" },
  { id: "sim_prop_3", address: "789 Sycamore Ln, Decatur, GA 30030", sqft: 1800, tier: "TIER_1" },
  { id: "sim_prop_4", address: "12 Riverbend Way, Smyrna, GA 30080", sqft: 4200, tier: "TIER_3" },
  { id: "sim_prop_5", address: "999 Grand Estate Pkwy, Roswell, GA 30075", sqft: 12000, tier: "CUSTOM" },
];

export const SYNTHETIC_CONTACTS = [
  { id: "sim_contact_1", name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142", company: "Premier Realty Group", stage: "lead", owner: "You" },
  { id: "sim_contact_2", name: "Marcus Johnson", email: "m.johnson@sim.example", phone: "(770) 555-0198", company: "Johnson & Associates", stage: "opportunity", owner: "You" },
  { id: "sim_contact_3", name: "Priya Patel", email: "p.patel@sim.example", phone: "(404) 555-0177", company: "Keller Williams Intown", stage: "mql", owner: "You" },
  { id: "sim_contact_4", name: "James Wilson", email: "j.wilson@sim.example", phone: "(404) 555-0166", company: "Buckhead Realty", stage: "customer", owner: "You" },
];

export const SYNTHETIC_PIPELINE_STAGES = ["lead", "mql", "sql", "opportunity", "customer"];

export const SYNTHETIC_MEDIA_SPECIALIST = {
  id: "sim_ms_1",
  name: "Alex Rivera",
  role: "Media Specialist",
  capabilities: ["photography", "videography", "drone"],
  assigned_jobs: 3,
  completed_jobs: 47,
  // NOTE: Provider payout details are NOT exposed to customers or in customer-facing scenarios.
};

// --- Jordan Smith Realty (fictional customer for onboarding/training finals) ---
export const JORDAN_SMITH_REALTY = {
  name: "Jordan Smith",
  company: "Jordan Smith Realty",
  email: "jordan.smith@sim.example",
  phone: "(404) 555-0301",
  market: "Atlanta, GA",
  property_address: "1450 Peachtree St NE, Atlanta, GA 30309",
  property_sqft: 2800,
  listing_timeline: "Listing goes live in 2 weeks",
  media_needs: ["photo", "video"],
  is_preferred: false,
};

// --- Customer Full Lifecycle Phases ---
export const CUSTOMER_LIFECYCLE_PHASES = [
  { id: "discovery", label: "Service & Package Discovery", description: "Understand the customer's listing-media needs." },
  { id: "pricing", label: "Live-Equivalent Pricing", description: "Calculate pricing using the same persisted pricing logic as production." },
  { id: "booking", label: "Booking", description: "Guide the customer through the booking form." },
  { id: "project_status", label: "Project Status", description: "Track the project through capture and delivery." },
  { id: "deliverables", label: "Deliverables", description: "Show the customer where to find their delivered media." },
  { id: "billing", label: "Invoice / Billing / Membership", description: "Explain billing and membership where applicable." },
  { id: "support", label: "Support / Rebook", description: "Explain where to get help and how to rebook." },
  { id: "satisfaction", label: "Post-Service Satisfaction Check", description: "Check satisfaction within 1 business day." },
  { id: "followup", label: "Follow-Up", description: "Follow up 7–14 days later for relationship health." },
];

// --- Provider Boundary Lifecycle (customer-visible only, no internal payout) ---
export const PROVIDER_LIFECYCLE_STEPS = [
  { id: "provider_qualification", label: "Provider Qualification", description: "A Media Specialist is matched based on verified capabilities and coverage area.", customer_visible: true },
  { id: "job_board", label: "Job Board", description: "The job appears on the Job Board for qualified Media Specialists.", customer_visible: true },
  { id: "accepted_assignment", label: "Accepted Assignment", description: "A Media Specialist accepts the assignment. Customer is notified.", customer_visible: true },
  { id: "capture", label: "On-Site Capture", description: "The Media Specialist captures photos/videos on site. Customer gets status updates.", customer_visible: true },
  { id: "deliverable", label: "Deliverable", description: "Edited media is delivered to the customer.", customer_visible: true },
  { id: "payout_status", label: "Payout Status (Internal)", description: "Provider payout is processed after fulfillment. This is internal — not shared with the customer.", customer_visible: false },
];

// --- Scenarios ---
export const SCENARIOS = [
  // === WATCH IT ===
  {
    id: "prospect_research",
    version: 1,
    level: "WATCH_IT",
    title: "Prospect Research & Professional Video Gate",
    description: "Observe how to research a prospect and perform the professional video check before making contact.",
    role: "sales_rep",
    type: "prospect_research",
    criticality: "high",
    initial_state: {
      prospects: SYNTHETIC_PROSPECTS,
      selected_prospect_id: null,
      video_check_done: false,
      video_check_result: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "prospect_search",
        title: "Step 1: Find a Prospect",
        description: "Search MLS listings to find an active real estate agent with a property listing.",
        guidance: "Watch how a prospect is selected from the research list. Every prospect must be researched before contact.",
        ui_type: "search_list",
        ui_config: { data_key: "prospects", search_placeholder: "Search agents, brokers, builders...", display_fields: ["name", "role", "brokerage", "market"] },
        expected_action: "select_prospect",
        expected_category: "prospect_selection",
        criticality: "high",
      },
      {
        screen: "professional_video_check",
        title: "Step 2: Professional Video Check",
        description: "Check whether the prospect's listing already has professional video.",
        guidance: "The professional video check determines whether a media opportunity exists. Skipping this is a critical failure.",
        ui_type: "video_check",
        ui_config: { prospect_key: "selected_prospect_id" },
        expected_action: "check_professional_video",
        expected_category: "video_check",
        criticality: "critical",
      },
      {
        screen: "research_summary",
        title: "Step 3: Research Summary",
        description: "Review the research summary and confirm the prospect is qualified for contact.",
        guidance: "Confirm the research is complete and the prospect qualifies for outreach.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "confirm_research",
        expected_category: "research_confirmation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["select_prospect", "check_professional_video", "confirm_research"],
      critical_failures: ["skip_video_check", "create_real_prospect", "contact_without_research"],
    },
  },

  // === FOLLOW IT ===
  {
    id: "crm_pipeline",
    version: 1,
    level: "FOLLOW_IT",
    title: "CRM Pipeline Navigation",
    description: "Follow guided prompts to navigate the Arriv One CRM pipeline and move a contact through stages.",
    role: "sales_rep",
    type: "crm_pipeline",
    criticality: "normal",
    initial_state: {
      contacts: SYNTHETIC_CONTACTS,
      pipeline_stages: SYNTHETIC_PIPELINE_STAGES,
      selected_contact_id: null,
      moved_contact_id: null,
      moved_to_stage: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "pipeline_view",
        title: "Step 1: View Your Pipeline",
        description: "Review your synthetic CRM pipeline with contacts at various lifecycle stages.",
        guidance: "This is a simulated pipeline. No real contacts are modified.",
        ui_type: "pipeline",
        ui_config: { contacts_key: "contacts", stages_key: "pipeline_stages" },
        expected_action: "select_contact",
        expected_category: "pipeline_navigation",
        criticality: "normal",
      },
      {
        screen: "contact_detail",
        title: "Step 2: Select a Contact to Advance",
        description: "Select a contact in the 'mql' or 'sql' stage to advance.",
        guidance: "Select Priya Patel (MQL) or Marcus Johnson (Opportunity) to advance through the pipeline.",
        ui_type: "info",
        ui_config: { show_contact_detail: true },
        expected_action: "advance_contact",
        expected_category: "stage_advancement",
        criticality: "normal",
      },
      {
        screen: "log_activity",
        title: "Step 3: Log Activity",
        description: "Log a simulated call or email activity for the contact.",
        guidance: "Every pipeline action should be accompanied by an activity log entry.",
        ui_type: "form",
        ui_config: { fields: [{ key: "activity_type", label: "Activity Type", type: "select", options: ["call", "email", "meeting"] }, { key: "notes", label: "Notes", type: "textarea" }] },
        expected_action: "log_activity",
        expected_category: "activity_logging",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["select_contact", "advance_contact", "log_activity"],
      critical_failures: ["create_real_contact", "delete_real_contact"],
    },
  },

  // === DO IT ===
  {
    id: "discovery",
    version: 1,
    level: "DO_IT",
    title: "Discovery & Building the Right Order",
    description: "Practice discovery with a synthetic prospect to build the right media order.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      prospect: SYNTHETIC_PROSPECTS[0],
      discovery_data: { property_address: "", property_sqft: null, listing_timeline: "", media_needs: [], customer_priorities: "" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "discovery_intro",
        title: "Step 1: Open the Discovery Conversation",
        description: "Start the discovery with the synthetic prospect using a permission-based opener.",
        guidance: "Use the Arriv Sales Method: DISCOVER → RESEARCH → PROFESSIONAL VIDEO CHECK → QUALIFY → CONTACT.",
        ui_type: "info",
        ui_config: { show_prospect: true },
        expected_action: "start_discovery",
        expected_category: "discovery_opening",
        criticality: "normal",
      },
      {
        screen: "discovery_questions",
        title: "Step 2: Ask Discovery Questions",
        description: "Ask about property address, sqft, listing timeline, photo/video needs, and customer priorities.",
        guidance: "Reps must NOT invent pricing or promise specific providers during discovery.",
        ui_type: "form",
        ui_config: { fields: [{ key: "property_address", label: "Property Address", type: "text" }, { key: "property_sqft", label: "Property Sqft", type: "number" }, { key: "listing_timeline", label: "Listing Timeline", type: "text" }, { key: "media_needs", label: "Media Needs", type: "multiselect", options: ["photo", "video", "drone", "3d_tour"] }, { key: "customer_priorities", label: "Customer Priorities", type: "textarea" }] },
        expected_action: "submit_discovery",
        expected_category: "discovery_completion",
        criticality: "high",
      },
      {
        screen: "discovery_summary",
        title: "Step 3: Confirm Discovery Summary",
        description: "Review the discovery summary and confirm the right order will be built.",
        guidance: "Confirm the discovery data is accurate before proceeding to pricing.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "confirm_discovery",
        expected_category: "discovery_confirmation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["start_discovery", "submit_discovery", "confirm_discovery"],
      critical_failures: ["invent_pricing", "promise_specific_provider", "skip_discovery"],
    },
  },

  {
    id: "pricing_package",
    version: 1,
    level: "DO_IT",
    title: "Pricing & Package Selection",
    description: "Practice selecting the right package and calculating price based on property sqft.",
    role: "sales_rep",
    type: "pricing_package",
    criticality: "critical",
    initial_state: {
      properties: SYNTHETIC_PROPERTIES,
      selected_property_id: null,
      selected_package: null,
      selected_add_ons: [],
      preferred_active: false,
      pricing_result: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "property_selection",
        title: "Step 1: Select a Property",
        description: "Select a synthetic property to determine its pricing tier.",
        guidance: "Property sqft determines the pricing tier. Never invent sqft — use the provided data.",
        ui_type: "search_list",
        ui_config: { data_key: "properties", search_placeholder: "Search properties...", display_fields: ["address", "sqft"] },
        expected_action: "select_property",
        expected_category: "property_selection",
        criticality: "high",
      },
      {
        screen: "package_selection",
        title: "Step 2: Select a Package",
        description: "Select the right media package for the prospect's needs.",
        guidance: "The price is determined by the tier + package. Reps must NOT quote custom prices.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true },
        expected_action: "select_package",
        expected_category: "package_selection",
        criticality: "critical",
      },
      {
        screen: "add_ons",
        title: "Step 3: Review Add-Ons (Optional)",
        description: "Review available add-ons and select any that fit the customer's needs.",
        guidance: "Add-ons are optional. Preferred members get 10% off non-MLS packages.",
        ui_type: "form",
        ui_config: { fields: [{ key: "add_ons", label: "Add-Ons", type: "multiselect", options: ADD_ONS.map(a => a.id) }, { key: "preferred_active", label: "Preferred Member", type: "checkbox" }] },
        expected_action: "confirm_pricing",
        expected_category: "pricing_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["select_property", "select_package", "confirm_pricing"],
      critical_failures: ["invent_pricing", "promise_custom_price", "skip_tier_determination"],
    },
  },

  // === SOLVE IT ===
  {
    id: "first_booking",
    version: 1,
    level: "SOLVE_IT",
    title: "First Booking with Objection",
    description: "Handle a price objection during the first booking and guide the customer to the right package.",
    role: "sales_rep",
    type: "first_booking",
    criticality: "high",
    initial_state: {
      customer: { name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142" },
      property: SYNTHETIC_PROPERTIES[0],
      objection: "That's more expensive than the photographer I usually use.",
      selected_package: null,
      objection_handled: false,
      booking_confirmed: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "objection_intro",
        title: "Step 1: Acknowledge the Objection",
        description: "The customer objects to the price. Acknowledge and validate their concern.",
        guidance: "Handle price objections by focusing on value, convenience, and professional presentation — not by discounting.",
        ui_type: "info",
        ui_config: { show_objection: true },
        expected_action: "acknowledge_objection",
        expected_category: "objection_handling",
        criticality: "high",
      },
      {
        screen: "value_response",
        title: "Step 2: Respond with Value",
        description: "Explain the value of professional media vs. a basic photographer.",
        guidance: "Use the value connection: convenience, reliability, professional presentation, reduced coordination.",
        ui_type: "form",
        ui_config: { fields: [{ key: "value_response", label: "Your Value Response", type: "textarea", placeholder: "Explain the value of Arriv's professional media..." }] },
        expected_action: "respond_with_value",
        expected_category: "value_connection",
        criticality: "high",
      },
      {
        screen: "booking_form",
        title: "Step 3: Complete the Booking",
        description: "Guide the customer through the booking form with the right package.",
        guidance: "If a discount is needed, use the manager-approval discount workflow. No discretionary discounts.",
        ui_type: "booking_form",
        ui_config: { show_booking_form: true },
        expected_action: "confirm_booking",
        expected_category: "booking_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["acknowledge_objection", "respond_with_value", "confirm_booking"],
      critical_failures: ["offer_unauthorized_discount", "invent_pricing", "disparage_competitor"],
    },
  },

  {
    id: "post_service_followup",
    version: 1,
    level: "SOLVE_IT",
    title: "Post-Service Follow-Up",
    description: "Handle post-service follow-up and ask for a referral after a completed job.",
    role: "sales_rep",
    type: "post_service_followup",
    criticality: "normal",
    initial_state: {
      customer: { name: "James Wilson", email: "j.wilson@sim.example", phone: "(404) 555-0166", job_completed: true },
      followup_done: false,
      referral_requested: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "followup_intro",
        title: "Step 1: Post-Service Follow-Up (within 1 business day)",
        description: "Follow up with the customer within 1 business day of service completion.",
        guidance: "Post-service follow-up within 1 business day is required. Then 7-14 day relationship follow-up.",
        ui_type: "info",
        ui_config: { show_customer: true },
        expected_action: "start_followup",
        expected_category: "followup_initiation",
        criticality: "normal",
      },
      {
        screen: "followup_call",
        title: "Step 2: Check Satisfaction",
        description: "Ask the customer about their satisfaction with the service.",
        guidance: "Check satisfaction, address any concerns, and confirm deliverables were received.",
        ui_type: "form",
        ui_config: { fields: [{ key: "satisfaction_notes", label: "Satisfaction Notes", type: "textarea" }] },
        expected_action: "log_followup",
        expected_category: "followup_completion",
        criticality: "normal",
      },
      {
        screen: "referral_request",
        title: "Step 3: Request a Referral",
        description: "Ask the customer for a referral. Explain the referral program ($20 standard / $40 Preferred).",
        guidance: "Referral program: $20 standard credit, $40 Preferred credit. Never promise cash payouts.",
        ui_type: "form",
        ui_config: { fields: [{ key: "referral_ask", label: "Referral Request", type: "textarea", placeholder: "Ask for a referral..." }] },
        expected_action: "request_referral",
        expected_category: "referral_request",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["start_followup", "log_followup", "request_referral"],
      critical_failures: ["skip_followup", "promise_cash_payout", "promise_provider_details"],
    },
  },

  // === ONBOARD IT ===
  {
    id: "customer_onboarding",
    version: 1,
    level: "ONBOARD_IT",
    title: "Customer Onboarding",
    description: "Guide a new customer through the onboarding process after their first booking.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "normal",
    initial_state: {
      customer: { name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142", booking_confirmed: true },
      onboarding_steps: { welcome_sent: false, account_created: false, preferred_offered: false, first_service_scheduled: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "welcome_intro",
        title: "Step 1: Send Welcome Communication",
        description: "Send a simulated welcome message to the new customer.",
        guidance: "Welcome the customer and confirm their booking details. This is a simulated email — no real email is sent.",
        ui_type: "form",
        ui_config: { fields: [{ key: "welcome_message", label: "Welcome Message", type: "textarea", placeholder: "Welcome to Arriv Estate Media..." }] },
        expected_action: "send_welcome",
        expected_category: "welcome_communication",
        criticality: "normal",
      },
      {
        screen: "account_creation",
        title: "Step 2: Confirm Account Creation",
        description: "Confirm the customer's account has been created in the system.",
        guidance: "Customer conversion: lead → qualified → sale → convert to customer → customer account created → customer can book.",
        ui_type: "info",
        ui_config: { show_account_status: true },
        expected_action: "confirm_account",
        expected_category: "account_confirmation",
        criticality: "normal",
      },
      {
        screen: "preferred_offer",
        title: "Step 3: Offer Preferred Membership",
        description: "Offer the Preferred membership ($29.99/month, 10% discount on services).",
        guidance: "Preferred: $29.99/month, 10% off non-MLS packages, $5 off MLS. Never pressure — inform and offer.",
        ui_type: "boundary",
        ui_config: { show_preferred_offer: true, choices: [{ label: "Offer Preferred (correct)", action: "offer_preferred", correct: true }, { label: "Pressure customer to join", action: "pressure_preferred", correct: false, criticality: "warning" }] },
        expected_action: "offer_preferred",
        expected_category: "preferred_offer",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["send_welcome", "confirm_account", "offer_preferred"],
      critical_failures: ["pressure_preferred", "skip_onboarding", "promise_free_services"],
    },
  },

  {
    id: "customer_account",
    version: 1,
    level: "ONBOARD_IT",
    title: "Customer Account & Deliverables",
    description: "Walk through the customer account view and deliverables access.",
    role: "customer",
    type: "customer_account",
    criticality: "normal",
    initial_state: {
      customer_account: { name: "James Wilson", email: "j.wilson@sim.example", bookings: [{ id: "sim_booking_1", property: "123 Oakwood Dr", package: "Photo + Cinematic", status: "delivered", deliverables_url: "sim://deliverables/1" }], membership: "Preferred" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "customer_dashboard",
        title: "Step 1: View Customer Dashboard",
        description: "See the customer's perspective: their bookings, deliverables, and membership.",
        guidance: "This is the CUSTOMER view. Understand what customers see to better serve them.",
        ui_type: "customer_view",
        ui_config: { show_customer_dashboard: true },
        expected_action: "view_dashboard",
        expected_category: "customer_navigation",
        criticality: "low",
      },
      {
        screen: "deliverables",
        title: "Step 2: Access Deliverables",
        description: "Show how the customer accesses their delivered media.",
        guidance: "Deliverables are shared via a secure link. The customer does NOT see internal provider details.",
        ui_type: "customer_view",
        ui_config: { show_deliverables: true },
        expected_action: "view_deliverables",
        expected_category: "deliverable_access",
        criticality: "normal",
      },
      {
        screen: "membership_view",
        title: "Step 3: View Membership Benefits",
        description: "Review the Preferred membership benefits from the customer perspective.",
        guidance: "Customers see their discount benefits, not internal pricing logic.",
        ui_type: "customer_view",
        ui_config: { show_membership: true },
        expected_action: "view_membership",
        expected_category: "membership_view",
        criticality: "low",
      },
    ],
    validation: {
      required_actions: ["view_dashboard", "view_deliverables", "view_membership"],
      critical_failures: ["expose_provider_payout", "expose_internal_pricing"],
    },
  },

  {
    id: "billing_membership",
    version: 1,
    level: "ONBOARD_IT",
    title: "Billing & Membership Management",
    description: "Handle a billing question and explain membership benefits.",
    role: "sales_rep",
    type: "billing_membership",
    criticality: "normal",
    initial_state: {
      customer: { name: "James Wilson", email: "j.wilson@sim.example", membership: "Preferred", question: "Why was I charged $29.99?" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "billing_question",
        title: "Step 1: Acknowledge the Billing Question",
        description: "The customer asks about a $29.99 charge. Acknowledge and explain.",
        guidance: "The $29.99 is the Preferred monthly membership. Explain the benefits (10% off, $5 off MLS).",
        ui_type: "info",
        ui_config: { show_question: true },
        expected_action: "acknowledge_billing",
        expected_category: "billing_acknowledgment",
        criticality: "normal",
      },
      {
        screen: "explain_benefits",
        title: "Step 2: Explain Membership Benefits",
        description: "Explain the Preferred membership benefits clearly.",
        guidance: "Preferred: $29.99/month, 10% off non-MLS, $5 off MLS. Never promise refunds without manager approval.",
        ui_type: "form",
        ui_config: { fields: [{ key: "benefits_explanation", label: "Benefits Explanation", type: "textarea" }] },
        expected_action: "explain_benefits",
        expected_category: "benefits_explanation",
        criticality: "normal",
      },
      {
        screen: "resolve_question",
        title: "Step 3: Resolve the Question",
        description: "Confirm the customer understands and is satisfied with the explanation.",
        guidance: "If a refund is needed, escalate to manager. No discretionary refunds.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm understanding (correct)", action: "confirm_resolution", correct: true }, { label: "Promise a refund", action: "promise_refund", correct: false, criticality: "critical" }] },
        expected_action: "confirm_resolution",
        expected_category: "question_resolution",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["acknowledge_billing", "explain_benefits", "confirm_resolution"],
      critical_failures: ["promise_refund", "promise_free_services", "disparage_company"],
    },
  },

  // === TEACH IT ===
  {
    id: "customer_teachback",
    version: 1,
    level: "TEACH_IT",
    title: "Customer Teach-Back",
    description: "Explain the Arriv Estate Media service model back as if teaching a new customer.",
    role: "sales_rep",
    type: "customer_teachback",
    criticality: "high",
    initial_state: {
      teachback_responses: { what_we_sell: "", how_pricing_works: "", customer_value: "", media_specialist_role: "" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "teachback_intro",
        title: "Step 1: Explain What We Sell",
        description: "Explain what Arriv Estate Media sells to a new customer.",
        guidance: "We sell convenience, reliability, professional listing presentation, and reduced coordination.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain what Arriv Estate Media sells:", field_key: "what_we_sell" },
        expected_action: "submit_teachback_1",
        expected_category: "teachback_what_we_sell",
        criticality: "high",
      },
      {
        screen: "teachback_pricing",
        title: "Step 2: Explain How Pricing Works",
        description: "Explain the pricing model (sqft → tier → package → price).",
        guidance: "Pricing is determined by property sqft → tier → package. No invented pricing.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain how pricing works:", field_key: "how_pricing_works" },
        expected_action: "submit_teachback_2",
        expected_category: "teachback_pricing",
        criticality: "high",
      },
      {
        screen: "teachback_media_specialist",
        title: "Step 3: Explain the Media Specialist Role",
        description: "Explain the Media Specialist fulfillment role — without exposing internal payout details.",
        guidance: "Explain that Media Specialists capture and deliver media. Do NOT expose provider payout percentages or internal compensation.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain the Media Specialist role (without exposing internal payout details):", field_key: "media_specialist_role" },
        expected_action: "submit_teachback_3",
        expected_category: "teachback_media_specialist",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["submit_teachback_1", "submit_teachback_2", "submit_teachback_3"],
      critical_failures: ["expose_provider_payout", "invent_pricing", "promise_staging"],
    },
  },

  {
    id: "media_specialist_boundary",
    version: 1,
    level: "TEACH_IT",
    title: "Media Specialist Fulfillment Boundary",
    description: "Understand the Media Specialist lifecycle enough to explain fulfillment — without being trained as a photographer.",
    role: "media_specialist",
    type: "media_specialist_boundary",
    criticality: "critical",
    initial_state: {
      media_specialist: SYNTHETIC_MEDIA_SPECIALIST,
      lifecycle_steps: ["awaiting_capture", "on_site", "captured", "footage_uploaded", "editing", "quality_control", "delivered"],
      current_lifecycle_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "ms_intro",
        title: "Step 1: Understand the Media Specialist Role",
        description: "Learn the Media Specialist fulfillment lifecycle at a high level.",
        guidance: "Reps must understand the lifecycle enough to explain fulfillment, but must NOT be trained as photographers unless separately authorized.",
        ui_type: "media_specialist_view",
        ui_config: { show_role_overview: true },
        expected_action: "review_ms_role",
        expected_category: "role_understanding",
        criticality: "normal",
      },
      {
        screen: "ms_lifecycle",
        title: "Step 2: Walk Through the Fulfillment Lifecycle",
        description: "Walk through each lifecycle step from capture to delivery.",
        guidance: "Lifecycle: awaiting_capture → on_site → captured → footage_uploaded → editing → quality_control → delivered.",
        ui_type: "lifecycle",
        ui_config: { steps_key: "lifecycle_steps" },
        expected_action: "walk_lifecycle",
        expected_category: "lifecycle_understanding",
        criticality: "normal",
      },
      {
        screen: "boundary_check",
        title: "Step 3: Boundary Check",
        description: "Confirm you understand what a rep may and may not promise about Media Specialist fulfillment.",
        guidance: "Reps may explain the fulfillment process. Reps may NOT promise specific providers, payout details, or unauthorized turnaround guarantees.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Explain fulfillment process (correct)", action: "explain_fulfillment", correct: true }, { label: "Promise a specific photographer", action: "promise_provider", correct: false, criticality: "critical" }, { label: "Share provider payout %", action: "expose_payout", correct: false, criticality: "critical" }] },
        expected_action: "explain_fulfillment",
        expected_category: "boundary_understanding",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["review_ms_role", "walk_lifecycle", "explain_fulfillment"],
      critical_failures: ["promise_provider", "expose_payout", "promise_turnaround_guarantee"],
    },
  },

  // === PROVE IT ===
  {
    id: "project_lifecycle",
    version: 1,
    level: "PROVE_IT",
    title: "Project Lifecycle Management",
    description: "Manage a simulated project from booking through delivery, demonstrating full lifecycle understanding.",
    role: "sales_rep",
    type: "project_lifecycle",
    criticality: "high",
    initial_state: {
      project: { id: "sim_project_1", customer: "Sarah Chen", property: "123 Oakwood Dr NE, Atlanta, GA 30305", package: "photo_cinematic", status: "booked" },
      lifecycle: ["booked", "media_partner_assigned", "capture_scheduled", "captured", "footage_uploaded", "editing", "quality_control", "delivered"],
      current_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "project_overview",
        title: "Step 1: Review the Project",
        description: "Review the simulated project details and lifecycle stages.",
        guidance: "Understand the full project lifecycle from booking to delivery.",
        ui_type: "info",
        ui_config: { show_project: true },
        expected_action: "review_project",
        expected_category: "project_review",
        criticality: "normal",
      },
      {
        screen: "advance_lifecycle",
        title: "Step 2: Advance Through Lifecycle Stages",
        description: "Advance the project through each lifecycle stage.",
        guidance: "Each stage has dependencies. Don't skip stages. Footage must be uploaded before editing.",
        ui_type: "lifecycle",
        ui_config: { steps_key: "lifecycle", current_step_key: "current_step" },
        expected_action: "advance_lifecycle",
        expected_category: "lifecycle_advancement",
        criticality: "high",
      },
      {
        screen: "delivery_confirmation",
        title: "Step 3: Confirm Delivery",
        description: "Confirm the deliverables have been sent to the customer.",
        guidance: "Delivery is the final stage. Confirm the customer received their media. Do NOT upload real deliverables in simulation.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm simulated delivery", action: "confirm_delivery", correct: true }, { label: "Upload a real file", action: "upload_real_file", correct: false, criticality: "critical" }] },
        expected_action: "confirm_delivery",
        expected_category: "delivery_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["review_project", "advance_lifecycle", "confirm_delivery"],
      critical_failures: ["upload_real_file", "skip_lifecycle_stage", "charge_real_stripe"],
    },
  },

  {
    id: "final_certification",
    version: 1,
    level: "PROVE_IT",
    title: "Final Certification Scenario",
    description: "Demonstrate mastery across the full sales process in a final certification scenario.",
    role: "sales_rep",
    type: "final_certification",
    criticality: "critical",
    initial_state: {
      prospect: SYNTHETIC_PROSPECTS[1],
      property: SYNTHETIC_PROPERTIES[1],
      certification_steps: { research: false, video_check: false, discovery: false, pricing: false, booking: false, followup: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "cert_intro",
        title: "Step 1: Research the Prospect",
        description: "Start the certification by researching the prospect and performing the professional video check.",
        guidance: "This is the PROVE IT level. Demonstrate the full process without guidance.",
        ui_type: "video_check",
        ui_config: { prospect_key: "prospect" },
        expected_action: "cert_research",
        expected_category: "certification_research",
        criticality: "critical",
      },
      {
        screen: "cert_discovery_pricing",
        title: "Step 2: Discovery & Pricing",
        description: "Complete discovery and calculate the correct pricing for the property.",
        guidance: "Use the correct tier and package. No invented pricing.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true, property_key: "property" },
        expected_action: "cert_pricing",
        expected_category: "certification_pricing",
        criticality: "critical",
      },
      {
        screen: "cert_boundary",
        title: "Step 3: Boundary Certification",
        description: "Confirm you understand all critical boundaries.",
        guidance: "Final boundary check: no invented pricing, no unauthorized discounts, no provider payout exposure, no staging promises.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm all boundaries understood", action: "cert_confirm_boundaries", correct: true }, { label: "I'll offer custom discounts", action: "cert_custom_discount", correct: false, criticality: "critical" }, { label: "I'll share provider payouts", action: "cert_expose_payout", correct: false, criticality: "critical" }] },
        expected_action: "cert_confirm_boundaries",
        expected_category: "certification_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["cert_research", "cert_pricing", "cert_confirm_boundaries"],
      critical_failures: ["cert_custom_discount", "cert_expose_payout", "invent_pricing", "promise_staging", "upload_real_file", "charge_real_stripe"],
    },
  },

  // === E4: System Mastery (FOLLOW_IT) ===
  {
    id: "e4_system_mastery",
    version: 1,
    level: "FOLLOW_IT",
    title: "E4: Customer Lifecycle Navigation",
    description: "Follow guided prompts through the complete customer lifecycle: account, packages, booking, project, deliverables, invoices.",
    role: "sales_rep",
    type: "prospect_research",
    criticality: "normal",
    initial_state: {
      customer: JORDAN_SMITH_REALTY,
      lifecycle_phases: ["account", "packages", "booking", "project", "deliverables", "invoices"],
      current_phase: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e4_account",
        title: "Step 1: Customer Account",
        description: "Review the customer's account. One person may hold customer and Media Specialist profiles; role choice is separate.",
        guidance: "Client and Media Specialist share EM sign-in but have different role views. Sales reps use separate SalesLogin.",
        ui_type: "info",
        ui_config: { show_customer: true },
        expected_action: "e4_review_account",
        expected_category: "system_navigation",
        criticality: "normal",
      },
      {
        screen: "e4_packages_booking",
        title: "Step 2: Packages & Booking",
        description: "Navigate packages and the booking form. Booking uses live address/property pricing and supported package rules.",
        guidance: "Combined photo+video jobs may require one provider qualified for both.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "e4_review_packages",
        expected_category: "system_navigation",
        criticality: "normal",
      },
      {
        screen: "e4_project_deliverables",
        title: "Step 3: Project, Deliverables & Invoices",
        description: "Navigate project status, deliverables, and invoices. Customer sees projects/deliverables/invoices per implemented product.",
        guidance: "Customer does NOT see internal provider payout details. Provider eligibility = verified capabilities + coverage area.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "e4_review_project",
        expected_category: "system_navigation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["e4_review_account", "e4_review_packages", "e4_review_project"],
      critical_failures: ["create_real_prospect", "expose_provider_payout"],
    },
  },

  // === E6: Sales Method Branching (DO_IT) ===
  {
    id: "e6_sales_method_branching",
    version: 1,
    level: "DO_IT",
    title: "E6: Sales Method — Branching Outreach",
    description: "Execute the sales method with branching: DISCOVER → RESEARCH → VIDEO CHECK → QUALIFY → CONTACT → CRM → FOLLOW-UP.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      prospects: SYNTHETIC_PROSPECTS,
      prospect: SYNTHETIC_PROSPECTS[0],
      method_steps: ["discover", "research", "video_check", "qualify", "contact", "crm", "followup"],
      current_method_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e6_discover_research",
        title: "Step 1: Discover & Research",
        description: "Discover the prospect and research their listing. Do not fake relationships or misrepresent purpose.",
        guidance: "DISCOVER → RESEARCH comes first. Research property/business context before outreach.",
        ui_type: "search_list",
        ui_config: { data_key: "prospects", search_placeholder: "Search prospects...", display_fields: ["name", "role", "brokerage", "market"] },
        expected_action: "select_prospect",
        expected_category: "method_discover_research",
        criticality: "high",
      },
      {
        screen: "e6_video_check_qualify",
        title: "Step 2: Professional Video Check & Qualify",
        description: "Check professional video presence, then qualify the prospect for contact.",
        guidance: "Professional video check happens before qualification. Skipping it is a critical failure.",
        ui_type: "video_check",
        ui_config: { prospect_key: "prospect" },
        expected_action: "check_professional_video",
        expected_category: "method_video_check_qualify",
        criticality: "critical",
      },
      {
        screen: "e6_contact_crm_followup",
        title: "Step 3: Contact, CRM & Follow-Up",
        description: "Contact the prospect, log in CRM, and set follow-up. Every interaction needs result, notes, next action, due date.",
        guidance: "CRM accuracy matters as much as activity. Use actual stages and required fields.",
        ui_type: "form",
        ui_config: { fields: [{ key: "activity_type", label: "Activity Type", type: "select", options: ["call", "email", "meeting"] }, { key: "notes", label: "Notes (result, next action, due date)", type: "textarea" }] },
        expected_action: "log_activity",
        expected_category: "method_contact_crm",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["select_prospect", "check_professional_video", "log_activity"],
      critical_failures: ["skip_video_check", "contact_without_research", "create_real_prospect", "invent_pricing"],
    },
  },

  // === E8: Cold Calling Branching (DO_IT) ===
  {
    id: "e8_cold_calling_branching",
    version: 1,
    level: "DO_IT",
    title: "E8: Cold Calling — Five-Call Branching",
    description: "Practice five cold calls with branching prospect responses. Permission-based opener, no deceptive framing.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      prospect: SYNTHETIC_PROSPECTS[2],
      call_scenarios: [
        { response: "I'm busy right now", correct_action: "ask_permission_to_follow_up" },
        { response: "I already have a photographer", correct_action: "explore_backup_needs" },
        { response: "What's the price?", correct_action: "explain_pricing_from_engine" },
        { response: "Can you give me a discount?", correct_action: "submit_discount_request" },
        { response: "Tell me about your video", correct_action: "explain_professional_video_value" },
      ],
      current_call: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e8_opener",
        title: "Step 1: Permission-Based Opener",
        description: "Open the call with a permission-based opener. Identify yourself and Arriv Estate Media clearly. No deceptive service-call framing.",
        guidance: "Honest opener: identify yourself, ask permission to speak, move quickly to discovery.",
        ui_type: "form",
        ui_config: { fields: [{ key: "opener", label: "Your Opener", type: "textarea", placeholder: "Hi, this is [name] with Arriv Estate Media..." }] },
        expected_action: "e8_submit_opener",
        expected_category: "cold_call_opener",
        criticality: "high",
      },
      {
        screen: "e8_branching_responses",
        title: "Step 2: Handle Branching Responses",
        description: "Handle five prospect responses: busy, has photographer, asks price, asks discount, asks about video.",
        guidance: "Busy → ask permission to follow up. Has photographer → explore backup. Price → explain from engine. Discount → submit request. Video → explain professional video value.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Ask permission to follow up / explore backup needs (correct approach)", action: "e8_ask_permission", correct: true },
          { label: "Promise a discount to close the deal", action: "offer_unauthorized_discount", correct: false, criticality: "critical" },
          { label: "Invent a price on the spot", action: "invent_pricing", correct: false, criticality: "critical" },
        ]},
        expected_action: "e8_ask_permission",
        expected_category: "cold_call_branching",
        criticality: "high",
      },
      {
        screen: "e8_discovery_transition",
        title: "Step 3: Move to Discovery",
        description: "Transition from the opener to discovery. Ask about property type, timing, media process, video use, deliverables.",
        guidance: "Do not force a package before understanding need. Say 'Let me verify that for you' for anything uncertain.",
        ui_type: "form",
        ui_config: { fields: [{ key: "discovery_notes", label: "Discovery Notes", type: "textarea", placeholder: "Property type, timing, media needs..." }] },
        expected_action: "e8_start_discovery",
        expected_category: "cold_call_discovery",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["e8_submit_opener", "e8_ask_permission", "e8_start_discovery"],
      critical_failures: ["offer_unauthorized_discount", "invent_pricing", "disparage_competitor", "promise_staging"],
    },
  },

  // === E13: Boundary Classification (SOLVE_IT) ===
  {
    id: "e13_boundary_classification",
    version: 1,
    level: "SOLVE_IT",
    title: "E13: Classify Safe vs. Unsafe Promises",
    description: "Classify promises as safe or unsafe. Inventing pricing, unauthorized discounts, provider payout exposure, and staging promises are critical failures.",
    role: "sales_rep",
    type: "media_specialist_boundary",
    criticality: "critical",
    initial_state: {
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e13_pricing_boundary",
        title: "Step 1: Pricing Boundary",
        description: "Classify: 'I can give you a custom price of $150 for the MLS Walkthrough.'",
        guidance: "Reps must quote only live, persisted pricing. Inventing pricing is a critical failure.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Safe — quote from the pricing engine", action: "e13_safe_pricing", correct: true },
          { label: "Unsafe — invent a custom price", action: "invent_pricing", correct: false, criticality: "critical" },
        ]},
        expected_action: "e13_safe_pricing",
        expected_category: "boundary_pricing",
        criticality: "critical",
      },
      {
        screen: "e13_provider_boundary",
        title: "Step 2: Provider Payout Boundary",
        description: "Classify: 'Your Media Specialist gets paid $X for this job.'",
        guidance: "Provider payout details are internal. Do not expose them to customers.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Safe — explain fulfillment process only", action: "e13_safe_provider", correct: true },
          { label: "Unsafe — share provider payout details", action: "expose_provider_payout", correct: false, criticality: "critical" },
        ]},
        expected_action: "e13_safe_provider",
        expected_category: "boundary_provider",
        criticality: "critical",
      },
      {
        screen: "e13_staging_discount_boundary",
        title: "Step 3: Staging & Discount Boundaries",
        description: "Classify: 'I can quote you staging pricing and a launch date' and 'I'll give you 15% off right now.'",
        guidance: "Staging is NOT currently sellable. Discounts require manager approval. Both are critical failures if promised.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Safe — document staging interest, submit discount request", action: "e13_safe_staging_discount", correct: true },
          { label: "Unsafe — quote staging pricing", action: "promise_staging", correct: false, criticality: "critical" },
          { label: "Unsafe — promise unauthorized discount", action: "offer_unauthorized_discount", correct: false, criticality: "critical" },
        ]},
        expected_action: "e13_safe_staging_discount",
        expected_category: "boundary_staging_discount",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["e13_safe_pricing", "e13_safe_provider", "e13_safe_staging_discount"],
      critical_failures: ["invent_pricing", "expose_provider_payout", "promise_staging", "offer_unauthorized_discount"],
    },
  },

  // === E16: Jordan Smith Realty Onboarding (ONBOARD_IT) ===
  {
    id: "e16_jordan_onboarding",
    version: 1,
    level: "ONBOARD_IT",
    title: "E16: Onboard Jordan Smith Realty",
    description: "Jordan Smith Realty just became an Estate Media customer. Onboard Jordan: account access, service orientation, first-booking prep, billing/membership, support.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "high",
    initial_state: {
      customer: JORDAN_SMITH_REALTY,
      onboarding_steps: { welcome_sent: false, account_confirmed: false, service_oriented: false, first_booking_prepared: false, billing_explained: false, support_explained: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e16_welcome_account",
        title: "Step 1: Welcome & Account Access",
        description: "Send Jordan a welcome message and confirm account access. Account activation email includes a secure temporary password.",
        guidance: "If Jordan didn't receive the email, use the resend function. Never share passwords over the phone. Password exists only in the email.",
        ui_type: "form",
        ui_config: { fields: [{ key: "welcome_message", label: "Welcome Message to Jordan", type: "textarea", placeholder: "Welcome to Arriv Estate Media, Jordan..." }] },
        expected_action: "e16_send_welcome",
        expected_category: "jordan_onboarding_welcome",
        criticality: "high",
      },
      {
        screen: "e16_service_orientation",
        title: "Step 2: Service & Process Orientation",
        description: "Explain the service model, process, and what to expect. Cover packages, booking flow, project lifecycle, and deliverables.",
        guidance: "Onboarding includes account access, service/process orientation, first-booking readiness, billing/membership where applicable, and support.",
        ui_type: "form",
        ui_config: { fields: [{ key: "service_orientation", label: "Service & Process Orientation Notes", type: "textarea", placeholder: "Explain packages, booking, project lifecycle, deliverables..." }] },
        expected_action: "e16_orient_service",
        expected_category: "jordan_onboarding_orientation",
        criticality: "high",
      },
      {
        screen: "e16_first_booking_billing_support",
        title: "Step 3: First Booking Prep, Billing & Support",
        description: "Prepare Jordan's first booking, explain billing/membership, and explain where to get help.",
        guidance: "First booking: 1450 Peachtree St NE (2,800 sqft → TIER_1). Billing: pay-up-front or pay-at-closing. Preferred: $29.99/mo, 10% off. Support: chat, email, or rep.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Prepare first booking, explain billing & support (correct)", action: "e16_prepare_booking_support", correct: true },
          { label: "Pressure Jordan to join Preferred", action: "pressure_preferred", correct: false, criticality: "warning" },
          { label: "Promise a free service", action: "promise_free_services", correct: false, criticality: "critical" },
        ]},
        expected_action: "e16_prepare_booking_support",
        expected_category: "jordan_onboarding_booking_support",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["e16_send_welcome", "e16_orient_service", "e16_prepare_booking_support"],
      critical_failures: ["pressure_preferred", "promise_free_services", "skip_onboarding", "expose_provider_payout", "promise_staging"],
    },
  },

  // === E17: Jordan Customer Training (TEACH_IT) ===
  {
    id: "e17_jordan_customer_training",
    version: 1,
    level: "TEACH_IT",
    title: "E17: Train Jordan to Book & Find Deliverables",
    description: "Train simulated Jordan to successfully book a first listing-media project, find project/deliverables, understand billing/membership, and know where to get help.",
    role: "customer",
    type: "customer_teachback",
    criticality: "high",
    initial_state: {
      customer: JORDAN_SMITH_REALTY,
      training_steps: { booking_trained: false, deliverables_trained: false, billing_trained: false, help_trained: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e17_train_booking",
        title: "Step 1: Teach Jordan to Book",
        description: "Teach Jordan how to book a first listing-media project. Task-based teaching — let Jordan perform the task.",
        guidance: "Teach: select package → enter property address → select date/time → submit booking. Check understanding by having Jordan perform it.",
        ui_type: "teachback",
        ui_config: { prompt: "Teach Jordan how to book a first listing-media project (step by step):", field_key: "booking_training" },
        expected_action: "e17_submit_booking_training",
        expected_category: "jordan_training_booking",
        criticality: "high",
      },
      {
        screen: "e17_train_deliverables",
        title: "Step 2: Teach Jordan to Find Project & Deliverables",
        description: "Teach Jordan where to find their project status and delivered media.",
        guidance: "Customer sees projects/deliverables/invoices in their account. Teach Jordan to navigate to My Bookings and access deliverables.",
        ui_type: "teachback",
        ui_config: { prompt: "Teach Jordan where to find project status and deliverables:", field_key: "deliverables_training" },
        expected_action: "e17_submit_deliverables_training",
        expected_category: "jordan_training_deliverables",
        criticality: "high",
      },
      {
        screen: "e17_train_billing_help",
        title: "Step 3: Teach Billing/Membership & Where to Get Help",
        description: "Teach Jordan about billing, membership where applicable, and where to get help.",
        guidance: "Billing: invoices in account. Preferred: $29.99/mo, 10% off. Help: chat, email, or rep. Check understanding by having Jordan explain it back.",
        ui_type: "teachback",
        ui_config: { prompt: "Teach Jordan about billing/membership and where to get help:", field_key: "billing_help_training" },
        expected_action: "e17_submit_billing_help_training",
        expected_category: "jordan_training_billing_help",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["e17_submit_booking_training", "e17_submit_deliverables_training", "e17_submit_billing_help_training"],
      critical_failures: ["expose_provider_payout", "invent_pricing", "promise_staging", "feature_dump"],
    },
  },

  // === E19: Jordan Smith Realty Final Certification (PROVE_IT) ===
  {
    id: "e19_jordan_final_certification",
    version: 1,
    level: "PROVE_IT",
    title: "E19: Jordan Smith Realty — Final Certification",
    description: "Jordan Smith Realty became an EM customer. Onboard Jordan, prepare first booking, explain process/support. Then train Jordan to book, find deliverables, understand billing, and know where to get help.",
    role: "sales_rep",
    type: "final_certification",
    criticality: "critical",
    initial_state: {
      customer: JORDAN_SMITH_REALTY,
      property: { address: JORDAN_SMITH_REALTY.property_address, sqft: JORDAN_SMITH_REALTY.property_sqft },
      cert_steps: { onboarded: false, first_booking_prepared: false, trained: false, boundaries_confirmed: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "e19_onboard_jordan",
        title: "Step 1: Onboard Jordan Smith Realty",
        description: "Onboard Jordan: account access, service/process orientation, first-booking readiness, billing/membership, and support.",
        guidance: "This is the PROVE IT level. Demonstrate the full onboarding without guidance. Jordan Smith Realty just became a customer.",
        ui_type: "form",
        ui_config: { fields: [{ key: "onboarding_plan", label: "Jordan Onboarding Plan", type: "textarea", placeholder: "Account access, service orientation, first booking, billing, support..." }] },
        expected_action: "e19_onboard_jordan",
        expected_category: "jordan_final_onboarding",
        criticality: "critical",
      },
      {
        screen: "e19_prepare_first_booking",
        title: "Step 2: Prepare First Booking & Train Jordan",
        description: "Prepare Jordan's first booking (1450 Peachtree St NE, 2,800 sqft) and train Jordan to book, find deliverables, and understand billing.",
        guidance: "Use live-equivalent pricing. 2,800 sqft → TIER_1. Train Jordan task-by-task: booking, deliverables, billing, help.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true, property_key: "property" },
        expected_action: "e19_prepare_booking_train",
        expected_category: "jordan_final_booking_training",
        criticality: "critical",
      },
      {
        screen: "e19_boundary_certification",
        title: "Step 3: Boundary Certification",
        description: "Confirm all critical boundaries: no invented pricing, no unauthorized discounts, no provider payout exposure, no staging promises.",
        guidance: "Final boundary check. Identify one critical boundary and one escalation path.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm all boundaries understood (correct)", action: "e19_confirm_boundaries", correct: true },
          { label: "I'll offer custom discounts", action: "cert_custom_discount", correct: false, criticality: "critical" },
          { label: "I'll share provider payouts", action: "cert_expose_payout", correct: false, criticality: "critical" },
          { label: "I'll quote staging pricing", action: "promise_staging", correct: false, criticality: "critical" },
        ]},
        expected_action: "e19_confirm_boundaries",
        expected_category: "jordan_final_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["e19_onboard_jordan", "e19_prepare_booking_train", "e19_confirm_boundaries"],
      critical_failures: ["cert_custom_discount", "cert_expose_payout", "invent_pricing", "promise_staging", "upload_real_file", "charge_real_stripe", "expose_provider_payout"],
    },
  },

  // === Customer Full Lifecycle Simulation (ONBOARD_IT) ===
  {
    id: "customer_full_lifecycle",
    version: 1,
    level: "ONBOARD_IT",
    title: "Customer Full Lifecycle Simulation",
    description: "Guide a fictional real-estate customer through: discovery → live-equivalent pricing → booking → project status → deliverables → billing/membership → support/rebook → satisfaction check → follow-up.",
    role: "sales_rep",
    type: "project_lifecycle",
    criticality: "high",
    initial_state: {
      customer: JORDAN_SMITH_REALTY,
      property: { address: JORDAN_SMITH_REALTY.property_address, sqft: JORDAN_SMITH_REALTY.property_sqft },
      phases: CUSTOMER_LIFECYCLE_PHASES.map(p => p.id),
      current_phase: 0,
      selected_package: null,
      pricing_result: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "customer_discovery",
        title: "Step 1: Service & Package Discovery",
        description: "Understand Jordan's listing-media needs: property type, timing, media process, video use, deliverables, recurring needs.",
        guidance: "Do not force a package before understanding need. Ask about property type, timing, current media process, video use, deliverables.",
        ui_type: "form",
        ui_config: { fields: [{ key: "property_address", label: "Property Address", type: "text", placeholder: JORDAN_SMITH_REALTY.property_address }, { key: "property_sqft", label: "Property Sqft", type: "number" }, { key: "listing_timeline", label: "Listing Timeline", type: "text" }, { key: "media_needs", label: "Media Needs", type: "multiselect", options: ["photo", "video", "drone", "3d_tour"] }, { key: "customer_priorities", label: "Customer Priorities", type: "textarea" }] },
        expected_action: "customer_submit_discovery",
        expected_category: "customer_discovery",
        criticality: "high",
      },
      {
        screen: "customer_pricing_booking",
        title: "Step 2: Live-Equivalent Pricing & Booking",
        description: "Calculate pricing using the same persisted pricing logic as production, then guide Jordan through the booking form.",
        guidance: "2,800 sqft → TIER_1. Price from the engine, not invented. Booking uses live address/property pricing and supported package rules.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true, property_key: "property" },
        expected_action: "customer_confirm_pricing",
        expected_category: "customer_pricing_booking",
        criticality: "critical",
      },
      {
        screen: "customer_project_to_followup",
        title: "Step 3: Project → Deliverables → Billing → Support → Satisfaction → Follow-Up",
        description: "Track the project through capture and delivery, show deliverables, explain billing/membership, explain support/rebook, check satisfaction, and follow up.",
        guidance: "Satisfaction check within 1 business day. Follow-up 7–14 days later. Do NOT expose internal provider payout details.",
        ui_type: "customer_simulation",
        ui_config: { show_lifecycle: true },
        expected_action: "customer_complete_lifecycle",
        expected_category: "customer_lifecycle_completion",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["customer_submit_discovery", "customer_confirm_pricing", "customer_complete_lifecycle"],
      critical_failures: ["invent_pricing", "expose_provider_payout", "promise_staging", "offer_unauthorized_discount", "charge_real_stripe", "upload_real_file"],
    },
  },

  // === Provider Boundary & Customer Impact (TEACH_IT) ===
  {
    id: "provider_boundary_customer_impact",
    version: 1,
    level: "TEACH_IT",
    title: "Provider Boundary & Customer Impact",
    description: "Show how provider qualification, job board, accepted assignment, deliverable, and payout-status concepts affect the customer experience — without training the rep to perform provider craft or exposing internal payout splits.",
    role: "media_specialist",
    type: "media_specialist_boundary",
    criticality: "critical",
    initial_state: {
      media_specialist: SYNTHETIC_MEDIA_SPECIALIST,
      lifecycle_steps: PROVIDER_LIFECYCLE_STEPS,
      current_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "provider_qualification_job_board",
        title: "Step 1: Provider Qualification & Job Board",
        description: "Understand how a Media Specialist is qualified (verified capabilities + coverage area) and how jobs appear on the Job Board.",
        guidance: "Provider eligibility = verified capabilities + coverage area. Only verified capabilities determine job eligibility. Sales does NOT recruit providers through AO prospecting.",
        ui_type: "provider_boundary",
        ui_config: { show_qualification: true, show_job_board: true },
        expected_action: "provider_review_qualification",
        expected_category: "provider_qualification",
        criticality: "normal",
      },
      {
        screen: "provider_assignment_capture",
        title: "Step 2: Accepted Assignment & Capture",
        description: "Understand how a Media Specialist accepts an assignment and captures media on site. Customer gets status updates.",
        guidance: "Customer is notified at each stage: assigned, on the way, on site, completed. Reps may explain this process but may NOT promise specific providers.",
        ui_type: "provider_boundary",
        ui_config: { show_assignment: true, show_capture: true },
        expected_action: "provider_review_assignment",
        expected_category: "provider_assignment_capture",
        criticality: "normal",
      },
      {
        screen: "provider_deliverable_payout_boundary",
        title: "Step 3: Deliverable, Payout Status & Boundary Check",
        description: "Understand deliverable handoff and payout status — and confirm the boundary: payout details are internal, not shared with customers.",
        guidance: "Deliverable is customer-visible. Payout status is INTERNAL. Reps may NOT expose provider payout splits, alter payouts, or perform provider craft unless separately authorized.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Explain deliverable + keep payout internal (correct)", action: "provider_safe_boundary", correct: true },
          { label: "Share provider payout details with customer", action: "expose_provider_payout", correct: false, criticality: "critical" },
          { label: "Promise a specific Media Specialist", action: "promise_provider", correct: false, criticality: "critical" },
          { label: "Promise a specific turnaround guarantee", action: "promise_turnaround_guarantee", correct: false, criticality: "critical" },
        ]},
        expected_action: "provider_safe_boundary",
        expected_category: "provider_boundary_check",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["provider_review_qualification", "provider_review_assignment", "provider_safe_boundary"],
      critical_failures: ["expose_provider_payout", "promise_provider", "promise_turnaround_guarantee", "perform_provider_craft"],
    },
  },
];

export function getScenariosByLevel(level) {
  return SCENARIOS.filter(s => s.level === level);
}

export function getScenarioById(id) {
  return SCENARIOS.find(s => s.id === id);
}