// ============================================================================
// B2B SIMULATION SYNTHETIC DATA + SCENARIOS (14–30)
// ============================================================================
// All data here is SYNTHETIC. No real organizations, members, contracts, or
// credit ledgers are referenced. The simulation NEVER touches production B2B
// entities, Stripe, invoicing, or external APIs.
// ============================================================================

import { B2B_COMMERCIAL_AUTHORITY } from "./salesTrainingData";

// --- B2B Synthetic Organizations ---
export const SYNTHETIC_B2B_ORGANIZATIONS = [
  {
    id: "sim_org_1",
    legal_name: "Premier Realty Group LLC",
    display_name: "Premier Realty Group",
    market: "Atlanta, GA",
    plan_id: "business",
    monthly_price: 1500,
    annual_prepaid_price: 15000,
    monthly_credits: 3,
    implementation_fee: 1000,
    billing_frequency: "monthly",
    status: "prospect",
    member_count: 0,
    credits_allocated: 0,
    credits_available: 0,
    credits_consumed: 0,
    contract_id: null,
    contract_version_id: null,
    account_hold: false,
  },
  {
    id: "sim_org_2",
    legal_name: "Johnson & Associates Realty",
    display_name: "Johnson & Associates",
    market: "Marietta, GA",
    plan_id: "portfolio",
    monthly_price: 5000,
    annual_prepaid_price: null,
    monthly_credits: 10,
    implementation_fee: 2500,
    billing_frequency: "monthly",
    status: "active",
    member_count: 4,
    credits_allocated: 10,
    credits_available: 7,
    credits_consumed: 3,
    contract_id: "sim_ctr_2",
    contract_version_id: "sim_ctrv_2_v1",
    account_hold: false,
  },
  {
    id: "sim_org_3",
    legal_name: "Coastal Builders LLC",
    display_name: "Coastal Builders",
    market: "Smyrna, GA",
    plan_id: "developer",
    monthly_price: 7500,
    annual_prepaid_price: null,
    monthly_credits: 15,
    implementation_fee: 3500,
    billing_frequency: "monthly",
    status: "active",
    member_count: 6,
    credits_allocated: 15,
    credits_available: 9,
    credits_consumed: 6,
    contract_id: "sim_ctr_3",
    contract_version_id: "sim_ctrv_3_v1",
    account_hold: false,
  },
  {
    id: "sim_org_4",
    legal_name: "Buckhead Luxury Estates Inc",
    display_name: "Buckhead Luxury Estates",
    market: "Atlanta, GA",
    plan_id: "enterprise",
    monthly_price: 12500,
    annual_prepaid_price: null,
    monthly_credits: 25,
    implementation_fee: 5000,
    billing_frequency: "annual_prepaid",
    status: "active",
    member_count: 12,
    credits_allocated: 300, // annualized pool (25 × 12)
    credits_available: 280,
    credits_consumed: 20,
    contract_id: "sim_ctr_4",
    contract_version_id: "sim_ctrv_4_v1",
    account_hold: false,
  },
  {
    id: "sim_org_5",
    legal_name: "Decatur Homes Group",
    display_name: "Decatur Homes",
    market: "Decatur, GA",
    plan_id: "business_plus",
    monthly_price: 2500,
    annual_prepaid_price: null,
    monthly_credits: 5,
    implementation_fee: 1500,
    billing_frequency: "monthly",
    status: "past_due",
    member_count: 3,
    credits_allocated: 5,
    credits_available: 2,
    credits_consumed: 3,
    contract_id: "sim_ctr_5",
    contract_version_id: "sim_ctrv_5_v1",
    account_hold: true,
  },
];

// --- B2B Synthetic Members ---
export const SYNTHETIC_B2B_MEMBERS = [
  { id: "sim_member_1", organization_id: "sim_org_2", name: "Marcus Johnson", email: "marcus@johnsonrealty.sim.example", role: "COMPANY_ADMIN", signing_authority: true, status: "active" },
  { id: "sim_member_2", organization_id: "sim_org_2", name: "Lisa Anderson", email: "lisa@johnsonrealty.sim.example", role: "MEMBER", signing_authority: false, status: "active" },
  { id: "sim_member_3", organization_id: "sim_org_2", name: "Tom Brown", email: "tom@johnsonrealty.sim.example", role: "MEMBER", signing_authority: false, status: "active" },
  { id: "sim_member_4", organization_id: "sim_org_3", name: "Jennifer Lee", email: "jen@coastalbuilders.sim.example", role: "COMPANY_ADMIN", signing_authority: true, status: "active" },
  { id: "sim_member_5", organization_id: "sim_org_4", name: "Robert Sterling", email: "robert@buckheadluxury.sim.example", role: "COMPANY_ADMIN", signing_authority: true, status: "active" },
  { id: "sim_member_6", organization_id: "sim_org_5", name: "Patricia Davis", email: "patricia@decaturhomes.sim.example", role: "COMPANY_ADMIN", signing_authority: true, status: "active" },
];

// --- B2B Synthetic Credit Ledger ---
export const SYNTHETIC_B2B_CREDIT_LEDGER = [
  { id: "sim_ledger_1", organization_id: "sim_org_2", event_type: "PERIOD_ALLOCATION", amount: 10, balance_after: 10, reason: "Monthly allocation", timestamp: "2026-09-01T00:00:00Z" },
  { id: "sim_ledger_2", organization_id: "sim_org_2", event_type: "BOOKING_CONSUMPTION", amount: -3, balance_after: 7, reason: "Photo Essentials booking", timestamp: "2026-09-15T00:00:00Z" },
  { id: "sim_ledger_3", organization_id: "sim_org_3", event_type: "PERIOD_ALLOCATION", amount: 15, balance_after: 15, reason: "Monthly allocation", timestamp: "2026-09-01T00:00:00Z" },
  { id: "sim_ledger_4", organization_id: "sim_org_3", event_type: "BOOKING_CONSUMPTION", amount: -6, balance_after: 9, reason: "Premium Bundle bookings", timestamp: "2026-09-20T00:00:00Z" },
];

// --- B2B Synthetic Invoices ---
export const SYNTHETIC_B2B_INVOICES = [
  { id: "sim_inv_1", organization_id: "sim_org_2", invoice_type: "MONTHLY_RECURRING", amount: 5000, status: "paid", due_date: "2026-09-01", paid_date: "2026-09-01" },
  { id: "sim_inv_2", organization_id: "sim_org_3", invoice_type: "MONTHLY_RECURRING", amount: 7500, status: "paid", due_date: "2026-09-01", paid_date: "2026-09-01" },
  { id: "sim_inv_3", organization_id: "sim_org_4", invoice_type: "ANNUAL_PREPAID", amount: 125000, status: "paid", due_date: "2026-01-01", paid_date: "2026-01-01" },
  { id: "sim_inv_4", organization_id: "sim_org_5", invoice_type: "MONTHLY_RECURRING", amount: 2500, status: "overdue", due_date: "2026-09-01", paid_date: null },
  { id: "sim_inv_5", organization_id: "sim_org_1", invoice_type: "IMPLEMENTATION", amount: 1000, status: "draft", due_date: null, paid_date: null },
];

// --- B2B Plan Reference (from locked commercial authority) ---
export const B2B_PLANS = B2B_COMMERCIAL_AUTHORITY.plans;

// --- B2B Commission Authority ---
export const B2B_COMMISSION_AUTHORITY = B2B_COMMERCIAL_AUTHORITY.rep_compensation;

// --- B2B Scenarios (14–30) ---
export const B2B_SCENARIOS = [
  // 14. Recognize B2B signal inside normal prospecting
  {
    id: "b2b_recognize_signal",
    version: 1,
    level: "DO_IT",
    title: "B2B: Recognize B2B Signal While Prospecting",
    description: "While prospecting an individual agent, recognize the B2B signal (centralized purchasing, multiple users, shared credits) without abandoning the individual lead.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      prospect: { id: "sim_prospect_2", name: "Marcus Johnson", role: "Broker", brokerage: "Johnson & Associates", market: "Marietta, GA", has_professional_video: true, email: "m.johnson@sim.example", phone: "(770) 555-0198" },
      b2b_signals: ["multiple_agents_in_brokerage", "centralized_purchasing_question", "shared_media_needs"],
      individual_lead_preserved: false,
      b2b_opportunity_identified: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_signal_intro",
        title: "Step 1: Spot the B2B Signal",
        description: "While researching Marcus Johnson (Broker, Johnson & Associates), you notice 8 agents in the brokerage. Recognize the B2B signal.",
        guidance: "A brokerage or company name alone does NOT create a B2B opportunity. Look for centralized purchasing, multiple users, shared credits/capacity, standardization, or company administration.",
        ui_type: "info",
        ui_config: { show_prospect: true },
        expected_action: "b2b_identify_signal",
        expected_category: "b2b_signal_recognition",
        criticality: "high",
      },
      {
        screen: "b2b_preserve_individual",
        title: "Step 2: Preserve the Individual Lead",
        description: "Continue the individual conversation with Marcus. Do NOT abandon the individual lead to chase the B2B opportunity.",
        guidance: "Maintain new-pipeline creation while larger B2B opportunities develop. B2B is an extension, not a replacement.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Continue individual conversation AND note B2B signal (correct)", action: "b2b_preserve_and_note", correct: true },
          { label: "Abandon individual lead to pitch B2B immediately", action: "b2b_abandon_individual", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_preserve_and_note",
        expected_category: "b2b_individual_preservation",
        criticality: "critical",
      },
      {
        screen: "b2b_qualify_signal",
        title: "Step 3: Qualify the B2B Signal",
        description: "Ask qualifying questions: How many agents? Is purchasing centralized? Would shared credits make sense?",
        guidance: "Qualify: number of users, centralized vs decentralized purchasing, standardization needs, company administration interest.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "agent_count", label: "Number of agents/users", type: "number" },
          { key: "purchasing_model", label: "Purchasing model", type: "select", options: ["centralized", "decentralized", "mixed"] },
          { key: "shared_credits_interest", label: "Shared credits interest?", type: "select", options: ["yes", "no", "maybe"] },
        ]},
        expected_action: "b2b_submit_qualification",
        expected_category: "b2b_qualification",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_identify_signal", "b2b_preserve_and_note", "b2b_submit_qualification"],
      critical_failures: ["b2b_abandon_individual", "b2b_invent_pricing", "b2b_invent_credits"],
    },
  },

  // 15. Brokerage discovery and decision-map creation
  {
    id: "b2b_brokerage_discovery",
    version: 1,
    level: "DO_IT",
    title: "B2B: Brokerage Discovery & Decision Map",
    description: "Conduct B2B discovery with a brokerage: understand decision-makers, current media process, pain points, and create a decision map.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[0],
      decision_makers: [],
      current_process: "",
      pain_points: [],
      decision_map_created: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_dm_identification",
        title: "Step 1: Identify Decision-Makers",
        description: "Identify who makes purchasing decisions at Premier Realty Group. Map: owner, office manager, marketing director.",
        guidance: "B2B decision maps identify: economic buyer, technical buyer, user buyer, coach. Log each with name, role, and influence level.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "dm1_name", label: "Decision-Maker 1 Name", type: "text" },
          { key: "dm1_role", label: "Role", type: "text" },
          { key: "dm1_influence", label: "Influence Level", type: "select", options: ["economic_buyer", "technical_buyer", "user_buyer", "coach"] },
        ]},
        expected_action: "b2b_log_decision_maker",
        expected_category: "b2b_decision_maker_mapping",
        criticality: "high",
      },
      {
        screen: "b2b_current_process",
        title: "Step 2: Understand Current Media Process",
        description: "Understand how the brokerage currently handles listing media: individual agents, shared photographer, DIY, mixed.",
        guidance: "Understand current state before recommending. Ask: who handles media now, what works, what doesn't, what's the cost.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "current_process", label: "Current Media Process", type: "textarea" },
          { key: "pain_points", label: "Pain Points", type: "textarea" },
        ]},
        expected_action: "b2b_log_current_process",
        expected_category: "b2b_process_discovery",
        criticality: "high",
      },
      {
        screen: "b2b_decision_map",
        title: "Step 3: Create the Decision Map",
        description: "Synthesize findings into a decision map: who decides, what they care about, what the process looks like.",
        guidance: "A decision map is NOT a pitch. It's a structured understanding of how the organization buys.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_create_decision_map",
        expected_category: "b2b_decision_map_creation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_log_decision_maker", "b2b_log_current_process", "b2b_create_decision_map"],
      critical_failures: ["b2b_pitch_without_discovery", "b2b_invent_pricing", "b2b_skip_decision_map"],
    },
  },

  // 16. Approved tier recommendation
  {
    id: "b2b_tier_recommendation",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Approved Tier Recommendation",
    description: "Recommend the correct B2B tier based on discovery, using ONLY current approved pricing. No unauthorized discounts, credits, or term changes.",
    role: "sales_rep",
    type: "pricing_package",
    criticality: "critical",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[0],
      discovery: { agent_count: 8, monthly_bookings: 12, centralized_purchasing: true },
      recommended_plan: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_match_tier",
        title: "Step 1: Match Discovery to Tier",
        description: "Based on 8 agents, ~12 bookings/month, centralized purchasing — match to the correct plan tier.",
        guidance: "Business $1,500/mo (3 credits), Business Plus $2,500/mo (5 credits), Portfolio $5,000/mo (10 credits), Developer $7,500/mo (15 credits), Enterprise $12,500/mo (25 credits). Match credits to booking volume.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Portfolio $5,000/mo, 10 credits (correct for 12 bookings/mo)", action: "b2b_recommend_portfolio", correct: true },
          { label: "Business $1,500/mo, 3 credits (too few credits)", action: "b2b_recommend_business_wrong", correct: false, criticality: "warning" },
          { label: "Enterprise $12,500/mo, 25 credits (overkill for 12 bookings)", action: "b2b_recommend_enterprise_wrong", correct: false, criticality: "warning" },
        ]},
        expected_action: "b2b_recommend_portfolio",
        expected_category: "b2b_tier_matching",
        criticality: "critical",
      },
      {
        screen: "b2b_explain_value",
        title: "Step 2: Explain the Value",
        description: "Explain why Portfolio is the right tier: 10 credits covers 12 bookings with overage protection, centralized billing, shared credits.",
        guidance: "Explain value based on the plan's actual features. Do NOT invent additional features, discounts, or credit allocations.",
        ui_type: "form",
        ui_config: { fields: [{ key: "value_explanation", label: "Value Explanation", type: "textarea" }] },
        expected_action: "b2b_explain_tier_value",
        expected_category: "b2b_value_explanation",
        criticality: "high",
      },
      {
        screen: "b2b_no_unauthorized_changes",
        title: "Step 3: Confirm No Unauthorized Changes",
        description: "Confirm you will NOT alter credits, pricing, discounts, implementation, or contract terms without approval.",
        guidance: "Reps cannot alter credits, pricing, discounts, implementation, or contract terms. Escalate for out-of-authority terms.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm: no unauthorized changes (correct)", action: "b2b_confirm_no_changes", correct: true },
          { label: "Offer a custom discount to close the deal", action: "b2b_offer_custom_discount", correct: false, criticality: "critical" },
          { label: "Add extra credits to sweeten the deal", action: "b2b_add_extra_credits", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_no_changes",
        expected_category: "b2b_authority_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["b2b_recommend_portfolio", "b2b_explain_tier_value", "b2b_confirm_no_changes"],
      critical_failures: ["b2b_offer_custom_discount", "b2b_add_extra_credits", "b2b_invent_pricing", "b2b_alter_contract_terms"],
    },
  },

  // 17. Convert synthetic prospect to canonical organization
  {
    id: "b2b_convert_organization",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Convert Prospect to Organization",
    description: "Convert the synthetic Premier Realty Group prospect into a canonical B2B organization with the correct plan.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "critical",
    initial_state: {
      prospect: SYNTHETIC_B2B_ORGANIZATIONS[0],
      selected_plan: "portfolio",
      organization_created: false,
      contract_created: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_create_org",
        title: "Step 1: Create the Organization",
        description: "Create the synthetic B2B organization record with legal name, market, and plan.",
        guidance: "Organization creation is synthetic. No real B2B entity is created. The organization record captures legal name, display name, market, and selected plan.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "legal_name", label: "Legal Name", type: "text", placeholder: "Premier Realty Group LLC" },
          { key: "display_name", label: "Display Name", type: "text", placeholder: "Premier Realty Group" },
          { key: "market", label: "Market", type: "text", placeholder: "Atlanta, GA" },
        ]},
        expected_action: "b2b_submit_org_creation",
        expected_category: "b2b_organization_creation",
        criticality: "critical",
      },
      {
        screen: "b2b_create_contract",
        title: "Step 2: Create the Contract",
        description: "Create the synthetic B2B contract with the Portfolio plan terms locked.",
        guidance: "Contract creation locks the commercial terms: plan, price, credits, implementation fee, billing frequency. This is a versioned, immutable snapshot.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_submit_contract_creation",
        expected_category: "b2b_contract_creation",
        criticality: "critical",
      },
      {
        screen: "b2b_confirm_synthetic",
        title: "Step 3: Confirm Synthetic Only",
        description: "Confirm that no real B2B organization, contract, or Stripe subscription was created.",
        guidance: "This is simulation. No real Stripe charge, no real organization record, no real contract version. Fail-closed: if any production effect occurred, the simulation fails.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm: synthetic only, no production effects (correct)", action: "b2b_confirm_synthetic_only", correct: true },
          { label: "Attempt to create a real Stripe subscription", action: "b2b_charge_real_stripe", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_synthetic_only",
        expected_category: "b2b_synthetic_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["b2b_submit_org_creation", "b2b_submit_contract_creation", "b2b_confirm_synthetic_only"],
      critical_failures: ["b2b_charge_real_stripe", "b2b_create_real_org", "b2b_alter_contract_terms"],
    },
  },

  // 18. Assign company admin
  {
    id: "b2b_assign_admin",
    version: 1,
    level: "ONBOARD_IT",
    title: "B2B: Assign Company Admin",
    description: "Assign a company admin for the synthetic organization and explain their responsibilities.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      admin_candidate: { name: "Marcus Johnson", email: "marcus@johnsonrealty.sim.example" },
      admin_assigned: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_select_admin",
        title: "Step 1: Select the Company Admin",
        description: "Select Marcus Johnson as the company admin for Johnson & Associates.",
        guidance: "The company admin manages members, credits, and billing. They must have signing authority. Select the person who will administer the account.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "admin_name", label: "Admin Name", type: "text", placeholder: "Marcus Johnson" },
          { key: "admin_email", label: "Admin Email", type: "text", placeholder: "marcus@johnsonrealty.sim.example" },
        ]},
        expected_action: "b2b_submit_admin_selection",
        expected_category: "b2b_admin_selection",
        criticality: "high",
      },
      {
        screen: "b2b_explain_admin_role",
        title: "Step 2: Explain Admin Responsibilities",
        description: "Explain what the company admin can do: manage members, view credits, manage billing, assign signing authority.",
        guidance: "Admin responsibilities: invite/remove members, view credit balance, manage billing, assign signing authority. The admin is NOT an Arriv admin — they are a company-level admin for their organization.",
        ui_type: "form",
        ui_config: { fields: [{ key: "admin_explanation", label: "Admin Role Explanation", type: "textarea" }] },
        expected_action: "b2b_explain_admin_role",
        expected_category: "b2b_admin_role_explanation",
        criticality: "high",
      },
      {
        screen: "b2b_grant_signing_authority",
        title: "Step 3: Grant Signing Authority",
        description: "Grant signing authority to the admin so they can sign B2B agreements on behalf of the organization.",
        guidance: "Signing authority allows the admin to sign agreements. This is a synthetic grant — no real agreement signature occurs.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Grant signing authority (correct)", action: "b2b_grant_authority", correct: true },
          { label: "Sign the agreement yourself on their behalf", action: "b2b_sign_on_behalf", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_grant_authority",
        expected_category: "b2b_signing_authority",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_submit_admin_selection", "b2b_explain_admin_role", "b2b_grant_authority"],
      critical_failures: ["b2b_sign_on_behalf", "b2b_impersonate_customer_admin", "b2b_enter_financial_credentials"],
    },
  },

  // 19. Add member profiles and verify organization linkage
  {
    id: "b2b_add_members",
    version: 1,
    level: "ONBOARD_IT",
    title: "B2B: Add Members & Verify Linkage",
    description: "Add member profiles to the synthetic organization and verify they are correctly linked.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      members_to_add: [
        { name: "Lisa Anderson", email: "lisa@johnsonrealty.sim.example" },
        { name: "Tom Brown", email: "tom@johnsonrealty.sim.example" },
      ],
      members_added: 0,
      linkage_verified: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_add_member_profiles",
        title: "Step 1: Add Member Profiles",
        description: "Add Lisa Anderson and Tom Brown as members of Johnson & Associates.",
        guidance: "Members are linked to the organization. Each member gets their own login but shares the organization's credits. Do NOT add unrelated users to the organization.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "member1_name", label: "Member 1 Name", type: "text" },
          { key: "member1_email", label: "Member 1 Email", type: "text" },
          { key: "member2_name", label: "Member 2 Name", type: "text" },
          { key: "member2_email", label: "Member 2 Email", type: "text" },
        ]},
        expected_action: "b2b_submit_members",
        expected_category: "b2b_member_addition",
        criticality: "high",
      },
      {
        screen: "b2b_verify_linkage",
        title: "Step 2: Verify Organization Linkage",
        description: "Verify that each member is correctly linked to the Johnson & Associates organization.",
        guidance: "Each member must be linked to the correct organization_id. Unrelated users must NOT be in the organization. Verify before proceeding.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Verify all members linked to correct org (correct)", action: "b2b_verify_linkage", correct: true },
          { label: "Add a random user to inflate member count", action: "b2b_add_unrelated_user", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_verify_linkage",
        expected_category: "b2b_linkage_verification",
        criticality: "critical",
      },
      {
        screen: "b2b_explain_credits",
        title: "Step 3: Explain Shared Credits",
        description: "Explain how shared credits work: all members draw from the organization's monthly credit pool.",
        guidance: "Credits are shared across the organization. Monthly credits reset monthly (or annual pool for annual prepaid). Members consume from the shared pool.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_shared_credits",
        expected_category: "b2b_credit_explanation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["b2b_submit_members", "b2b_verify_linkage", "b2b_explain_shared_credits"],
      critical_failures: ["b2b_add_unrelated_user", "b2b_invent_credits", "b2b_alter_credit_allocation"],
    },
  },

  // 20. Explain and consume synthetic company credits
  {
    id: "b2b_consume_credits",
    version: 1,
    level: "DO_IT",
    title: "B2B: Explain & Consume Company Credits",
    description: "Explain how company credits work and simulate a booking that consumes credits from the organization's pool.",
    role: "sales_rep",
    type: "pricing_package",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      credits_before: 7,
      booking_credits_needed: 1,
      credits_after: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_credit_pool_explanation",
        title: "Step 1: Explain the Credit Pool",
        description: "Explain how the organization's credit pool works: 10 credits/month, reset monthly, shared across members.",
        guidance: "Credits are a shared organizational resource. Monthly plans reset monthly. Annual prepaid gets an annualized pool. Credits do NOT roll over.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_pool",
        expected_category: "b2b_credit_pool_explanation",
        criticality: "high",
      },
      {
        screen: "b2b_simulate_booking",
        title: "Step 2: Simulate a Credit-Consuming Booking",
        description: "Simulate a Photo Essentials booking that consumes 1 credit from the pool (7 → 6).",
        guidance: "Each booking consumes credits based on the package. Photo Essentials = 1 credit, Premium Bundle = 2 credits (varies by config). The ledger records the consumption.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Consume 1 credit for Photo Essentials (correct)", action: "b2b_consume_credit", correct: true },
          { label: "Consume 0 credits (free booking)", action: "b2b_free_booking", correct: false, criticality: "critical" },
          { label: "Consume 5 credits (overcharge)", action: "b2b_overcharge_credits", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_consume_credit",
        expected_category: "b2b_credit_consumption",
        criticality: "high",
      },
      {
        screen: "b2b_verify_ledger",
        title: "Step 3: Verify the Credit Ledger",
        description: "Verify the synthetic credit ledger shows the correct balance: 7 → 6 after consumption.",
        guidance: "The credit ledger is append-only. Each event has: event_type, amount, balance_before, balance_after, reason, timestamp. Verify the ledger is accurate.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_verify_ledger",
        expected_category: "b2b_ledger_verification",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_explain_pool", "b2b_consume_credit", "b2b_verify_ledger"],
      critical_failures: ["b2b_free_booking", "b2b_overcharge_credits", "b2b_invent_credits", "b2b_alter_credit_allocation"],
    },
  },

  // 21. Annual invoice at conversion
  {
    id: "b2b_annual_invoice",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Annual Invoice at Conversion",
    description: "Generate the synthetic annual invoice at B2B conversion using the canonical invoice infrastructure.",
    role: "sales_rep",
    type: "billing_membership",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[3], // Buckhead Luxury = annual prepaid
      invoice_type: "ANNUAL_PREPAID",
      invoice_amount: 125000,
      invoice_created: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_annual_invoice_explanation",
        title: "Step 1: Explain Annual Prepaid Invoicing",
        description: "Explain that annual prepaid B2B conversion uses the established invoice infrastructure — NOT a separate B2B invoice engine.",
        guidance: "B2B reuses the established invoice infrastructure. Do NOT create a second invoice engine. Annual conversion invokes the established invoice system.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_invoice_reuse",
        expected_category: "b2b_invoice_reuse",
        criticality: "high",
      },
      {
        screen: "b2b_generate_annual_invoice",
        title: "Step 2: Generate the Synthetic Annual Invoice",
        description: "Generate the synthetic annual invoice: $125,000 for Buckhead Luxury Estates (Enterprise annual prepaid).",
        guidance: "The invoice is synthetic. No real Stripe charge. The invoice captures: organization, amount, type (ANNUAL_PREPAID), status (draft → sent → paid).",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Generate synthetic annual invoice (correct)", action: "b2b_generate_invoice", correct: true },
          { label: "Charge the real Stripe account", action: "b2b_charge_real_stripe", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_generate_invoice",
        expected_category: "b2b_invoice_generation",
        criticality: "critical",
      },
      {
        screen: "b2b_verify_invoice",
        title: "Step 3: Verify the Invoice Record",
        description: "Verify the synthetic invoice record: correct amount, type, organization, and status.",
        guidance: "Invoice verification: organization_id, invoice_type, amount, status, due_date. This is a synthetic record — no real payment processing.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_verify_invoice",
        expected_category: "b2b_invoice_verification",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_explain_invoice_reuse", "b2b_generate_invoice", "b2b_verify_invoice"],
      critical_failures: ["b2b_charge_real_stripe", "b2b_create_second_invoice_engine", "b2b_invent_pricing"],
    },
  },

  // 22. Monthly recurring billing state
  {
    id: "b2b_monthly_billing",
    version: 1,
    level: "DO_IT",
    title: "B2B: Monthly Recurring Billing State",
    description: "Understand and explain the monthly recurring billing state for a B2B organization.",
    role: "sales_rep",
    type: "billing_membership",
    criticality: "normal",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1], // Johnson & Associates = monthly
      billing_state: "current",
      monthly_amount: 5000,
      next_invoice_date: "2026-10-01",
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_monthly_billing_explanation",
        title: "Step 1: Explain Monthly Recurring Billing",
        description: "Explain how monthly B2B billing works: $5,000/month, invoiced on the 1st, managed via connected recurring billing workflow.",
        guidance: "Monthly B2B customers use the connected recurring billing workflow. The invoice is generated monthly and processed through the established billing system.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_monthly",
        expected_category: "b2b_monthly_billing_explanation",
        criticality: "normal",
      },
      {
        screen: "b2b_billing_state_check",
        title: "Step 2: Check the Billing State",
        description: "Check the current billing state: current, past_due, or on_hold.",
        guidance: "Billing states: current (paid on time), past_due (invoice overdue), on_hold (account held due to non-payment). Each state has different implications.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Current — paid on time (correct)", action: "b2b_confirm_current", correct: true },
          { label: "Fake a paid state when the invoice is overdue", action: "b2b_fake_paid_state", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_current",
        expected_category: "b2b_billing_state",
        criticality: "high",
      },
      {
        screen: "b2b_next_invoice",
        title: "Step 3: Explain Next Invoice",
        description: "Explain when the next invoice will be generated and what it will include.",
        guidance: "Next invoice: October 1, $5,000, monthly recurring. Credits reset at the start of each billing period.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_next_invoice",
        expected_category: "b2b_next_invoice_explanation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["b2b_explain_monthly", "b2b_confirm_current", "b2b_explain_next_invoice"],
      critical_failures: ["b2b_fake_paid_state", "b2b_bypass_hold", "b2b_charge_real_stripe"],
    },
  },

  // 23. Failed/overdue payment and account hold
  {
    id: "b2b_account_hold",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Failed Payment & Account Hold",
    description: "Handle a failed/overdue payment and account hold scenario for a B2B organization.",
    role: "sales_rep",
    type: "billing_membership",
    criticality: "critical",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[4], // Decatur Homes = past_due + on hold
      billing_state: "past_due",
      account_hold: true,
      hold_reason: "Invoice overdue — September 2026",
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_hold_acknowledgment",
        title: "Step 1: Acknowledge the Account Hold",
        description: "Acknowledge that Decatur Homes has an account hold due to an overdue invoice. Do NOT bypass the hold.",
        guidance: "Account hold means credits are frozen and new bookings are blocked. The rep must NOT bypass the hold, fake a paid state, or use privileged financial operations.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_acknowledge_hold",
        expected_category: "b2b_hold_acknowledgment",
        criticality: "critical",
      },
      {
        screen: "b2b_hold_boundary",
        title: "Step 2: Respect the Hold Boundary",
        description: "Confirm you will NOT bypass the hold, fake a paid state, or enter financial credentials on behalf of the customer.",
        guidance: "The customer admin handles their own financial actions. The rep explains, demonstrates, troubleshoots, and trains — but does NOT impersonate the customer admin, enter financial credentials, fake a paid state, or bypass a hold.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Explain the hold and the resolution path (correct)", action: "b2b_explain_hold_resolution", correct: true },
          { label: "Bypass the hold to let them book", action: "b2b_bypass_hold", correct: false, criticality: "critical" },
          { label: "Fake a paid state in the system", action: "b2b_fake_paid_state", correct: false, criticality: "critical" },
          { label: "Enter their credit card on their behalf", action: "b2b_enter_financial_credentials", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_explain_hold_resolution",
        expected_category: "b2b_hold_resolution",
        criticality: "critical",
      },
      {
        screen: "b2b_customer_admin_resolution",
        title: "Step 3: Guide the Customer Admin to Resolve",
        description: "Guide the customer admin (Patricia Davis) to resolve the hold themselves through their authorized financial actions.",
        guidance: "The customer admin logs in, updates payment method, and the hold is released by the system. The rep supports but does NOT perform the financial action.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_guide_admin_resolution",
        expected_category: "b2b_admin_resolution_guidance",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_acknowledge_hold", "b2b_explain_hold_resolution", "b2b_guide_admin_resolution"],
      critical_failures: ["b2b_bypass_hold", "b2b_fake_paid_state", "b2b_enter_financial_credentials", "b2b_impersonate_customer_admin"],
    },
  },

  // 24. Company-admin onboarding and teach-back
  {
    id: "b2b_admin_onboarding",
    version: 1,
    level: "ONBOARD_IT",
    title: "B2B: Company-Admin Onboarding & Teach-Back",
    description: "Onboard the company admin and verify their understanding through teach-back.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      admin: SYNTHETIC_B2B_MEMBERS[0],
      onboarding_steps: { welcome_sent: false, admin_role_explained: false, credits_explained: false, members_trained: false },
      teachback_verified: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_admin_welcome",
        title: "Step 1: Welcome the Company Admin",
        description: "Send a synthetic welcome to Marcus Johnson, the company admin for Johnson & Associates.",
        guidance: "Welcome the admin, confirm their role, and explain what they can do: manage members, view credits, manage billing.",
        ui_type: "form",
        ui_config: { fields: [{ key: "welcome_message", label: "Welcome Message", type: "textarea" }] },
        expected_action: "b2b_send_admin_welcome",
        expected_category: "b2b_admin_welcome",
        criticality: "high",
      },
      {
        screen: "b2b_admin_credits_training",
        title: "Step 2: Train on Credits & Members",
        description: "Train the admin on credit management and member management.",
        guidance: "Explain: credit pool, monthly reset, member invitations, member removal, signing authority. Let the admin perform tasks in simulation.",
        ui_type: "form",
        ui_config: { fields: [{ key: "training_notes", label: "Training Notes", type: "textarea" }] },
        expected_action: "b2b_train_admin_credits",
        expected_category: "b2b_admin_credits_training",
        criticality: "high",
      },
      {
        screen: "b2b_admin_teachback",
        title: "Step 3: Admin Teach-Back",
        description: "Have the admin explain back: how credits work, how to add members, how to manage billing.",
        guidance: "Teach-back verifies understanding. The admin should be able to explain credit pool, member management, and billing without prompting.",
        ui_type: "teachback",
        ui_config: { prompt: "Have the admin explain back: how credits work, how to add members, how to manage billing:", field_key: "admin_teachback" },
        expected_action: "b2b_submit_admin_teachback",
        expected_category: "b2b_admin_teachback",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_send_admin_welcome", "b2b_train_admin_credits", "b2b_submit_admin_teachback"],
      critical_failures: ["b2b_skip_onboarding", "b2b_impersonate_customer_admin", "b2b_enter_financial_credentials"],
    },
  },

  // 25. Under-utilization/customer-success recovery
  {
    id: "b2b_underutilization_recovery",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Under-Utilization & Customer-Success Recovery",
    description: "Identify under-utilization of B2B credits and execute a customer-success recovery plan.",
    role: "sales_rep",
    type: "post_service_followup",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      credits_allocated: 10,
      credits_consumed: 3,
      utilization_rate: 30,
      recovery_plan_created: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_identify_underutilization",
        title: "Step 1: Identify Under-Utilization",
        description: "Identify that Johnson & Associates is under-utilizing their credits: 3 of 10 consumed (30%).",
        guidance: "Under-utilization is a customer-success risk. If credits expire unused, the customer may not renew. Identify early and act.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_identify_underutilization",
        expected_category: "b2b_underutilization_identification",
        criticality: "high",
      },
      {
        screen: "b2b_root_cause",
        title: "Step 2: Diagnose the Root Cause",
        description: "Diagnose why credits are under-utilized: members not trained, adoption gap, wrong tier, or process friction.",
        guidance: "Root causes: members don't know how to book, admin hasn't invited all agents, wrong tier (too many credits), process too complex. Ask, don't assume.",
        ui_type: "form",
        ui_config: { fields: [{ key: "root_cause", label: "Root Cause Analysis", type: "textarea" }] },
        expected_action: "b2b_submit_root_cause",
        expected_category: "b2b_root_cause_analysis",
        criticality: "high",
      },
      {
        screen: "b2b_recovery_plan",
        title: "Step 3: Create a Recovery Plan",
        description: "Create a customer-success recovery plan: retrain members, simplify process, or recommend tier adjustment.",
        guidance: "Recovery options: retrain members, help admin invite missing agents, simplify the booking process, or recommend a tier adjustment (downgrade is NOT a discount — it's matching the customer's actual needs). Do NOT invent credits or alter the contract.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Retrain members + help admin invite agents (correct)", action: "b2b_recovery_retrain", correct: true },
          { label: "Give them free credits to compensate", action: "b2b_free_credits", correct: false, criticality: "critical" },
          { label: "Alter the contract to reduce their commitment", action: "b2b_alter_contract", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_recovery_retrain",
        expected_category: "b2b_recovery_plan",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_identify_underutilization", "b2b_submit_root_cause", "b2b_recovery_retrain"],
      critical_failures: ["b2b_free_credits", "b2b_alter_contract", "b2b_invent_credits"],
    },
  },

  // 26. Expansion without unauthorized terms
  {
    id: "b2b_expansion",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Expansion Without Unauthorized Terms",
    description: "Handle a B2B expansion opportunity without altering credits, pricing, or contract terms without approval.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "critical",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[1],
      expansion_request: "Add 5 more agents and increase credits to 20/month",
      current_plan: "portfolio",
      current_credits: 10,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_expansion_qualification",
        title: "Step 1: Qualify the Expansion",
        description: "Qualify the expansion request: 5 more agents, 20 credits/month needed. Current plan is Portfolio (10 credits).",
        guidance: "Expansion means moving to a higher tier (Developer = 15 credits or Enterprise = 25 credits) or adding a contract amendment. Qualify the actual need first.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_qualify_expansion",
        expected_category: "b2b_expansion_qualification",
        criticality: "high",
      },
      {
        screen: "b2b_expansion_recommendation",
        title: "Step 2: Recommend the Correct Expansion",
        description: "Recommend the correct expansion path: upgrade to Developer ($7,500/mo, 15 credits) or Enterprise ($12,500/mo, 25 credits).",
        guidance: "20 credits/month → Enterprise (25 credits) is the closest match. Do NOT invent a custom plan or custom credit allocation.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Recommend Enterprise upgrade $12,500/mo, 25 credits (correct)", action: "b2b_recommend_enterprise_upgrade", correct: true },
          { label: "Invent a custom 20-credit plan at a custom price", action: "b2b_invent_custom_plan", correct: false, criticality: "critical" },
          { label: "Add 10 extra credits to the existing Portfolio plan for free", action: "b2b_free_extra_credits", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_recommend_enterprise_upgrade",
        expected_category: "b2b_expansion_recommendation",
        criticality: "critical",
      },
      {
        screen: "b2b_expansion_escalation",
        title: "Step 3: Escalate for Approval",
        description: "Escalate the expansion for contract amendment approval. The rep cannot alter the contract terms themselves.",
        guidance: "Expansion requires a contract amendment or new contract version. The rep initiates the expansion but does NOT alter the contract terms. Escalate to the approved system.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_escalate_expansion",
        expected_category: "b2b_expansion_escalation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_qualify_expansion", "b2b_recommend_enterprise_upgrade", "b2b_escalate_expansion"],
      critical_failures: ["b2b_invent_custom_plan", "b2b_free_extra_credits", "b2b_alter_contract_terms", "b2b_invent_pricing"],
    },
  },

  // 27. Renewal conversation
  {
    id: "b2b_renewal",
    version: 1,
    level: "SOLVE_IT",
    title: "B2B: Renewal Conversation",
    description: "Conduct a renewal conversation with a B2B customer whose contract is approaching renewal.",
    role: "sales_rep",
    type: "post_service_followup",
    criticality: "high",
    initial_state: {
      organization: SYNTHETIC_B2B_ORGANIZATIONS[2],
      contract_end_date: "2026-12-31",
      renewal_type: "auto_renew",
      utilization_rate: 80,
      satisfaction: "high",
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_renewal_review",
        title: "Step 1: Review the Account Before Renewal",
        description: "Review Coastal Builders' account: utilization, satisfaction, expansion opportunities, and renewal terms.",
        guidance: "Before a renewal conversation, review: utilization rate, satisfaction, expansion opportunities, and the current contract's renewal type (auto_renew, manual_renew, month_to_month).",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_review_renewal_account",
        expected_category: "b2b_renewal_review",
        criticality: "high",
      },
      {
        screen: "b2b_renewal_conversation",
        title: "Step 2: Conduct the Renewal Conversation",
        description: "Conduct the renewal conversation: confirm satisfaction, discuss utilization, and confirm renewal terms.",
        guidance: "Renewal conversation: confirm satisfaction, review utilization, discuss any expansion needs, and confirm renewal terms. Do NOT alter terms without approval.",
        ui_type: "form",
        ui_config: { fields: [{ key: "renewal_notes", label: "Renewal Conversation Notes", type: "textarea" }] },
        expected_action: "b2b_submit_renewal_notes",
        expected_category: "b2b_renewal_conversation",
        criticality: "high",
      },
      {
        screen: "b2b_renewal_confirmation",
        title: "Step 3: Confirm Renewal Terms",
        description: "Confirm the renewal will proceed on the existing terms (auto-renew) or initiate a renewal amendment if changes are needed.",
        guidance: "Auto-renew: contract continues on existing terms. If changes are needed (expansion, tier change), initiate a contract amendment through the approved system. Do NOT alter terms verbally.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm auto-renew on existing terms (correct)", action: "b2b_confirm_auto_renew", correct: true },
          { label: "Verbally agree to different terms without a contract amendment", action: "b2b_verbal_terms_change", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_auto_renew",
        expected_category: "b2b_renewal_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["b2b_review_renewal_account", "b2b_submit_renewal_notes", "b2b_confirm_auto_renew"],
      critical_failures: ["b2b_verbal_terms_change", "b2b_alter_contract_terms", "b2b_invent_pricing"],
    },
  },

  // 28. B2B compensation interpretation
  {
    id: "b2b_compensation",
    version: 1,
    level: "TEACH_IT",
    title: "B2B: Compensation Interpretation",
    description: "Interpret B2B rep compensation correctly: 60% implementation, 15% month-1, 8% thereafter, stops on departure.",
    role: "sales_rep",
    type: "customer_teachback",
    criticality: "high",
    initial_state: {
      deal: { plan: "portfolio", implementation_fee: 2500, monthly_price: 5000, term: "monthly" },
      compensation_calculated: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_comp_explanation",
        title: "Step 1: Explain the B2B Commission Structure",
        description: "Explain: 60% of collected implementation fees, 15% of collected subscription revenue in month 1, 8% thereafter while employed.",
        guidance: "B2B commission: 60% implementation, 15% month-1 subscription, 8% thereafter. Recurring stops at employment separation. No residual, buyout, acceleration, or post-employment recurring.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_compensation",
        expected_category: "b2b_compensation_explanation",
        criticality: "high",
      },
      {
        screen: "b2b_comp_calculation",
        title: "Step 2: Calculate the Commission",
        description: "Calculate: Portfolio deal — $2,500 implementation × 60% = $1,500. Month 1: $5,000 × 15% = $750. Month 2+: $5,000 × 8% = $400/month.",
        guidance: "Implementation: $2,500 × 60% = $1,500. Month 1: $5,000 × 15% = $750. Month 2+: $5,000 × 8% = $400/month. Use current approved authority — do NOT invent rates.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "implementation_commission", label: "Implementation Commission ($)", type: "number" },
          { key: "month1_commission", label: "Month 1 Commission ($)", type: "number" },
          { key: "ongoing_commission", label: "Ongoing Monthly Commission ($)", type: "number" },
        ]},
        expected_action: "b2b_submit_compensation_calc",
        expected_category: "b2b_compensation_calculation",
        criticality: "critical",
      },
      {
        screen: "b2b_comp_boundary",
        title: "Step 3: Confirm Compensation Boundaries",
        description: "Confirm: recurring stops on departure, no residual, no buyout, no acceleration, no post-employment recurring.",
        guidance: "Recurring commission stops when the rep leaves. No continuing residual, buyout, acceleration, or post-employment recurring payout. This is the current approved authority.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm all compensation boundaries (correct)", action: "b2b_confirm_comp_boundaries", correct: true },
          { label: "Claim continuing residual after departure", action: "b2b_claim_residual", correct: false, criticality: "critical" },
          { label: "Invent a higher commission rate", action: "b2b_invent_rate", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_comp_boundaries",
        expected_category: "b2b_compensation_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["b2b_explain_compensation", "b2b_submit_compensation_calc", "b2b_confirm_comp_boundaries"],
      critical_failures: ["b2b_claim_residual", "b2b_invent_rate", "b2b_invent_pricing"],
    },
  },

  // 29. Balanced-week planning
  {
    id: "b2b_balanced_week",
    version: 1,
    level: "TEACH_IT",
    title: "B2B: Balanced-Week Planning",
    description: "Plan a balanced sales week that maintains individual prospecting while developing B2B opportunities.",
    role: "sales_rep",
    type: "customer_teachback",
    criticality: "high",
    initial_state: {
      week_plan: { individual_prospecting_days: 0, b2b_development_hours: 0, pipeline_advancement_hours: 0, customer_onboarding_hours: 0 },
      balance_achieved: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_balance_explanation",
        title: "Step 1: Explain the Sales Motion Mix",
        description: "Explain the four sales motions: Individual/SMB Prospecting, B2B Development, Pipeline Advancement, Customer Onboarding/Expansion.",
        guidance: "Sales Motion Mix: 1) Individual/SMB Prospecting, 2) B2B Development, 3) Pipeline Advancement, 4) Customer Onboarding/Expansion. B2B is an extension, not a replacement.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_explain_motion_mix",
        expected_category: "b2b_motion_mix_explanation",
        criticality: "high",
      },
      {
        screen: "b2b_week_plan",
        title: "Step 2: Plan a Balanced Week",
        description: "Plan a week that includes: 3 full prospecting days (~300 attempts), B2B development, pipeline advancement, and customer onboarding.",
        guidance: "~100 outbound attempts on a full remote prospecting day. ~400/week only when four true full prospecting days occur. Qualified demos, field work, onboarding, and training reduce prospecting time. Plan for the mix.",
        ui_type: "form",
        ui_config: { fields: [
          { key: "prospecting_days", label: "Full Prospecting Days", type: "number" },
          { key: "b2b_hours", label: "B2B Development Hours", type: "number" },
          { key: "pipeline_hours", label: "Pipeline Advancement Hours", type: "number" },
          { key: "onboarding_hours", label: "Customer Onboarding Hours", type: "number" },
        ]},
        expected_action: "b2b_submit_week_plan",
        expected_category: "b2b_week_planning",
        criticality: "high",
      },
      {
        screen: "b2b_balance_verification",
        title: "Step 3: Verify Balance",
        description: "Verify the plan maintains individual prospecting while developing B2B. No abandonment of individual pipeline.",
        guidance: "Anti-gaming: B2B time should NOT dominate for 2+ weeks while new-pipeline creation materially falls. Maintain balance. Due follow-up >=95%, CRM completeness >=95%.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm balanced plan with maintained prospecting (correct)", action: "b2b_confirm_balance", correct: true },
          { label: "Abandon prospecting for B2B-only week", action: "b2b_abandon_prospecting", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_confirm_balance",
        expected_category: "b2b_balance_verification",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["b2b_explain_motion_mix", "b2b_submit_week_plan", "b2b_confirm_balance"],
      critical_failures: ["b2b_abandon_prospecting", "b2b_abandon_individual", "b2b_invent_pricing"],
    },
  },

  // 30. Full prospect-to-adoption B2B certification
  {
    id: "b2b_final_certification",
    version: 1,
    level: "PROVE_IT",
    title: "B2B: Full Prospect-to-Adoption Certification",
    description: "Demonstrate mastery of the full B2B lifecycle: recognize signal → discover → recommend → convert → assign admin → add members → consume credits → onboard → adopt → expand.",
    role: "sales_rep",
    type: "final_certification",
    criticality: "critical",
    initial_state: {
      prospect: SYNTHETIC_B2B_ORGANIZATIONS[0],
      cert_steps: { signal_recognized: false, discovery_done: false, recommended: false, converted: false, admin_assigned: false, members_added: false, credits_consumed: false, onboarded: false, adopted: false, boundaries_confirmed: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "b2b_cert_signal_discovery",
        title: "Step 1: Recognize Signal & Discover",
        description: "Recognize the B2B signal in Premier Realty Group and conduct discovery: decision-makers, current process, pain points.",
        guidance: "This is the PROVE IT level. Demonstrate the full B2B process without guidance. Preserve the individual lead while qualifying the B2B opportunity.",
        ui_type: "form",
        ui_config: { fields: [{ key: "discovery_summary", label: "B2B Discovery Summary", type: "textarea" }] },
        expected_action: "b2b_cert_discover",
        expected_category: "b2b_cert_discovery",
        criticality: "critical",
      },
      {
        screen: "b2b_cert_convert_onboard",
        title: "Step 2: Recommend, Convert & Onboard",
        description: "Recommend the correct tier, convert to organization, assign admin, add members, and onboard.",
        guidance: "Use ONLY current approved pricing. No unauthorized discounts, credits, or term changes. Synthetic only — no real Stripe, no real org creation.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "b2b_cert_convert_onboard",
        expected_category: "b2b_cert_conversion_onboarding",
        criticality: "critical",
      },
      {
        screen: "b2b_cert_boundary",
        title: "Step 3: Boundary Certification",
        description: "Confirm all B2B boundaries: no invented pricing, no unauthorized credits, no contract term changes, no customer admin impersonation, no financial credential entry, no hold bypass.",
        guidance: "Final B2B boundary check. The rep cannot alter credits, pricing, discounts, implementation, or contract terms. The rep cannot impersonate the customer admin or enter financial credentials.",
        ui_type: "boundary",
        ui_config: { choices: [
          { label: "Confirm all B2B boundaries understood (correct)", action: "b2b_cert_confirm_boundaries", correct: true },
          { label: "I'll offer custom B2B discounts", action: "b2b_cert_custom_discount", correct: false, criticality: "critical" },
          { label: "I'll enter customer financial credentials", action: "b2b_cert_enter_credentials", correct: false, criticality: "critical" },
          { label: "I'll bypass account holds", action: "b2b_cert_bypass_hold", correct: false, criticality: "critical" },
        ]},
        expected_action: "b2b_cert_confirm_boundaries",
        expected_category: "b2b_cert_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["b2b_cert_discover", "b2b_cert_convert_onboard", "b2b_cert_confirm_boundaries"],
      critical_failures: ["b2b_cert_custom_discount", "b2b_cert_enter_credentials", "b2b_cert_bypass_hold", "b2b_invent_pricing", "b2b_invent_credits", "b2b_alter_contract_terms", "b2b_charge_real_stripe", "b2b_create_real_org", "b2b_impersonate_customer_admin"],
    },
  },
];

export function getB2BScenariosByLevel(level) {
  return B2B_SCENARIOS.filter(s => s.level === level);
}

export function getB2BScenarioById(id) {
  return B2B_SCENARIOS.find(s => s.id === id);
}