// ============================================================================
// TRAINING SIMULATION SCENARIOS — Synthetic data + scenario definitions
// ============================================================================
// All data here is SYNTHETIC. No real prospects, customers, properties, or
// business records are referenced. The simulation never touches production
// entities or APIs. See simulationEngine.js for the reducer + validation.
// ============================================================================

export const SIMULATION_LEVELS = [
  { id: "WATCH_IT", label: "Watch It", description: "Observe the correct process step-by-step.", color: "#6B7280" },
  { id: "FOLLOW_IT", label: "Follow It", description: "Follow guided prompts through the workflow.", color: "#3B82F6" },
  { id: "DO_IT", label: "Do It", description: "Perform the workflow with minimal guidance.", color: "#B8956A" },
  { id: "SOLVE_IT", label: "Solve It", description: "Handle objections and edge cases.", color: "#F59E0B" },
  { id: "ONBOARD_IT", label: "Onboard It", description: "Guide a customer through onboarding.", color: "#8B5CF6" },
  { id: "TEACH_IT", label: "Teach It", description: "Explain the process back to demonstrate mastery.", color: "#EC4899" },
  { id: "PROVE_IT", label: "Prove It", description: "Final certification scenario.", color: "#EF4444" },
];

// --- Pricing (mirrors DEFAULT_PRICING_CONFIG from mediaPricingEngine.ts) ---
export const PRICING_TIERS = [
  { tier: "TIER_1", min: 0, max: 2500, label: "Up to 2,500 sqft", prices: { mls_walkthrough: 100, photo_essentials: 275, photo_cinematic: 475, premium_bundle: 675 } },
  { tier: "TIER_2", min: 2501, max: 3500, label: "2,501–3,500 sqft", prices: { mls_walkthrough: 125, photo_essentials: 325, photo_cinematic: 525, premium_bundle: 750 } },
  { tier: "TIER_3", min: 3501, max: 5000, label: "3,501–5,000 sqft", prices: { mls_walkthrough: 150, photo_essentials: 375, photo_cinematic: 575, premium_bundle: 825 } },
  { tier: "TIER_4", min: 5001, max: 7500, label: "5,001–7,500 sqft", prices: { mls_walkthrough: 200, photo_essentials: 450, photo_cinematic: 650, premium_bundle: 950 } },
  { tier: "TIER_5", min: 7501, max: 10000, label: "7,501–10,000 sqft", prices: { mls_walkthrough: 275, photo_essentials: 575, photo_cinematic: 775, premium_bundle: 1100 } },
  { tier: "CUSTOM", min: 10001, max: Infinity, label: "10,001+ sqft (Custom Quote)", prices: {} },
];

export const PACKAGES = [
  { id: "mls_walkthrough", name: "MLS Walkthrough", description: "Zillow-style 45-second walkthrough video" },
  { id: "photo_essentials", name: "Photo Essentials", description: "Professional photography package" },
  { id: "photo_cinematic", name: "Photo + Cinematic", description: "Photography + cinematic video" },
  { id: "premium_bundle", name: "Premium Bundle", description: "Full premium media package" },
];

export const ADD_ONS = [
  { id: "drone", name: "Drone add-on (photos + short clips)", price: 125 },
  { id: "3d_tour", name: "3D Tour", price: 125 },
  { id: "twilight", name: "Twilight exterior edits (up to 5 photos)", price: 125 },
  { id: "rush_delivery", name: "Next-day rush delivery (when available)", price: 100 },
  { id: "vertical_reel", name: "Additional vertical reel", price: 40 },
  { id: "ai_staging", name: "AI Staging", price: 125 },
];

export const PREFERRED_CONFIG = { monthly_price: 29.99, regular_discount_rate: 0.10, mls_flat_discount: 5.00 };

// --- Synthetic Data ---
export const SYNTHETIC_PROSPECTS = [
  { id: "sim_prospect_1", name: "Sarah Chen", role: "Real Estate Agent", brokerage: "Premier Realty Group", market: "Atlanta, GA", listing_address: "123 Oakwood Dr NE, Atlanta, GA 30305", listing_price: 450000, listing_sqft: 2200, has_professional_video: false, email: "s.chen@sim.example", phone: "(404) 555-0142" },
  { id: "sim_prospect_2", name: "Marcus Johnson", role: "Broker", brokerage: "Johnson & Associates", market: "Marietta, GA", listing_address: "456 Maple St, Marietta, GA 30060", listing_price: 625000, listing_sqft: 3100, has_professional_video: true, email: "m.johnson@sim.example", phone: "(770) 555-0198" },
  { id: "sim_prospect_3", name: "Priya Patel", role: "Real Estate Agent", brokerage: "Keller Williams Intown", market: "Decatur, GA", listing_address: "789 Sycamore Ln, Decatur, GA 30030", listing_price: 385000, listing_sqft: 1800, has_professional_video: false, email: "p.patel@sim.example", phone: "(404) 555-0177" },
  { id: "sim_prospect_4", name: "Coastal Builders LLC", role: "Builder", brokerage: "Coastal Builders", market: "Smyrna, GA", listing_address: "12 Riverbend Way, Smyrna, GA 30080", listing_price: 890000, listing_sqft: 4200, has_professional_video: false, email: "info@coastalbuilders.sim.example", phone: "(770) 555-0233" },
];

export const SYNTHETIC_PROPERTIES = [
  { id: "sim_prop_1", address: "123 Oakwood Dr NE, Atlanta, GA 30305", sqft: 2200, tier: "TIER_1" },
  { id: "sim_prop_2", address: "456 Maple St, Marietta, GA 30060", sqft: 3100, tier: "TIER_2" },
  { id: "sim_prop_3", address: "789 Sycamore Ln, Decatur, GA 30030", sqft: 1800, tier: "TIER_1" },
  { id: "sim_prop_4", address: "12 Riverbend Way, Smyrna, GA 30080", sqft: 4200, tier: "TIER_3" },
  { id: "sim_prop_5", address: "999 Grand Estate Pkwy, Roswell, GA 30075", sqft: 12000, tier: "CUSTOM" },
];

export const SYNTHETIC_CONTACTS = [
  { id: "sim_contact_1", name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142", company: "Premier Realty Group", stage: "lead", owner: "You" },
  { id: "sim_contact_2", name: "Marcus Johnson", email: "m.johnson@sim.example", phone: "(770) 555-0198", company: "Johnson & Associates", stage: "opportunity", owner: "You" },
  { id: "sim_contact_3", name: "Priya Patel", email: "p.patel@sim.example", phone: "(404) 555-0177", company: "Keller Williams Intown", stage: "mql", owner: "You" },
  { id: "sim_contact_4", name: "James Wilson", email: "j.wilson@sim.example", phone: "(404) 555-0166", company: "Buckhead Realty", stage: "customer", owner: "You" },
];

export const SYNTHETIC_PIPELINE_STAGES = ["lead", "mql", "sql", "opportunity", "customer"];

export const SYNTHETIC_MEDIA_SPECIALIST = {
  id: "sim_ms_1",
  name: "Alex Rivera",
  role: "Media Specialist",
  capabilities: ["photography", "videography", "drone"],
  assigned_jobs: 3,
  completed_jobs: 47,
  // NOTE: Provider payout details are NOT exposed to customers or in customer-facing scenarios.
};

// --- Scenarios ---
export const SCENARIOS = [
  // === WATCH IT ===
  {
    id: "prospect_research",
    version: 1,
    level: "WATCH_IT",
    title: "Prospect Research & Professional Video Gate",
    description: "Observe how to research a prospect and perform the professional video check before making contact.",
    role: "sales_rep",
    type: "prospect_research",
    criticality: "high",
    initial_state: {
      prospects: SYNTHETIC_PROSPECTS,
      selected_prospect_id: null,
      video_check_done: false,
      video_check_result: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "prospect_search",
        title: "Step 1: Find a Prospect",
        description: "Search MLS listings to find an active real estate agent with a property listing.",
        guidance: "Watch how a prospect is selected from the research list. Every prospect must be researched before contact.",
        ui_type: "search_list",
        ui_config: { data_key: "prospects", search_placeholder: "Search agents, brokers, builders...", display_fields: ["name", "role", "brokerage", "market"] },
        expected_action: "select_prospect",
        expected_category: "prospect_selection",
        criticality: "high",
      },
      {
        screen: "professional_video_check",
        title: "Step 2: Professional Video Check",
        description: "Check whether the prospect's listing already has professional video.",
        guidance: "The professional video check determines whether a media opportunity exists. Skipping this is a critical failure.",
        ui_type: "video_check",
        ui_config: { prospect_key: "selected_prospect_id" },
        expected_action: "check_professional_video",
        expected_category: "video_check",
        criticality: "critical",
      },
      {
        screen: "research_summary",
        title: "Step 3: Research Summary",
        description: "Review the research summary and confirm the prospect is qualified for contact.",
        guidance: "Confirm the research is complete and the prospect qualifies for outreach.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "confirm_research",
        expected_category: "research_confirmation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["select_prospect", "check_professional_video", "confirm_research"],
      critical_failures: ["skip_video_check", "create_real_prospect", "contact_without_research"],
    },
  },

  // === FOLLOW IT ===
  {
    id: "crm_pipeline",
    version: 1,
    level: "FOLLOW_IT",
    title: "CRM Pipeline Navigation",
    description: "Follow guided prompts to navigate the Arriv One CRM pipeline and move a contact through stages.",
    role: "sales_rep",
    type: "crm_pipeline",
    criticality: "normal",
    initial_state: {
      contacts: SYNTHETIC_CONTACTS,
      pipeline_stages: SYNTHETIC_PIPELINE_STAGES,
      selected_contact_id: null,
      moved_contact_id: null,
      moved_to_stage: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "pipeline_view",
        title: "Step 1: View Your Pipeline",
        description: "Review your synthetic CRM pipeline with contacts at various lifecycle stages.",
        guidance: "This is a simulated pipeline. No real contacts are modified.",
        ui_type: "pipeline",
        ui_config: { contacts_key: "contacts", stages_key: "pipeline_stages" },
        expected_action: "select_contact",
        expected_category: "pipeline_navigation",
        criticality: "normal",
      },
      {
        screen: "contact_detail",
        title: "Step 2: Select a Contact to Advance",
        description: "Select a contact in the 'mql' or 'sql' stage to advance.",
        guidance: "Select Priya Patel (MQL) or Marcus Johnson (Opportunity) to advance through the pipeline.",
        ui_type: "info",
        ui_config: { show_contact_detail: true },
        expected_action: "advance_contact",
        expected_category: "stage_advancement",
        criticality: "normal",
      },
      {
        screen: "log_activity",
        title: "Step 3: Log Activity",
        description: "Log a simulated call or email activity for the contact.",
        guidance: "Every pipeline action should be accompanied by an activity log entry.",
        ui_type: "form",
        ui_config: { fields: [{ key: "activity_type", label: "Activity Type", type: "select", options: ["call", "email", "meeting"] }, { key: "notes", label: "Notes", type: "textarea" }] },
        expected_action: "log_activity",
        expected_category: "activity_logging",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["select_contact", "advance_contact", "log_activity"],
      critical_failures: ["create_real_contact", "delete_real_contact"],
    },
  },

  // === DO IT ===
  {
    id: "discovery",
    version: 1,
    level: "DO_IT",
    title: "Discovery & Building the Right Order",
    description: "Practice discovery with a synthetic prospect to build the right media order.",
    role: "sales_rep",
    type: "discovery",
    criticality: "high",
    initial_state: {
      prospect: SYNTHETIC_PROSPECTS[0],
      discovery_data: { property_address: "", property_sqft: null, listing_timeline: "", media_needs: [], customer_priorities: "" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "discovery_intro",
        title: "Step 1: Open the Discovery Conversation",
        description: "Start the discovery with the synthetic prospect using a permission-based opener.",
        guidance: "Use the Arriv Sales Method: DISCOVER → RESEARCH → PROFESSIONAL VIDEO CHECK → QUALIFY → CONTACT.",
        ui_type: "info",
        ui_config: { show_prospect: true },
        expected_action: "start_discovery",
        expected_category: "discovery_opening",
        criticality: "normal",
      },
      {
        screen: "discovery_questions",
        title: "Step 2: Ask Discovery Questions",
        description: "Ask about property address, sqft, listing timeline, photo/video needs, and customer priorities.",
        guidance: "Reps must NOT invent pricing or promise specific providers during discovery.",
        ui_type: "form",
        ui_config: { fields: [{ key: "property_address", label: "Property Address", type: "text" }, { key: "property_sqft", label: "Property Sqft", type: "number" }, { key: "listing_timeline", label: "Listing Timeline", type: "text" }, { key: "media_needs", label: "Media Needs", type: "multiselect", options: ["photo", "video", "drone", "3d_tour"] }, { key: "customer_priorities", label: "Customer Priorities", type: "textarea" }] },
        expected_action: "submit_discovery",
        expected_category: "discovery_completion",
        criticality: "high",
      },
      {
        screen: "discovery_summary",
        title: "Step 3: Confirm Discovery Summary",
        description: "Review the discovery summary and confirm the right order will be built.",
        guidance: "Confirm the discovery data is accurate before proceeding to pricing.",
        ui_type: "info",
        ui_config: { show_summary: true },
        expected_action: "confirm_discovery",
        expected_category: "discovery_confirmation",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["start_discovery", "submit_discovery", "confirm_discovery"],
      critical_failures: ["invent_pricing", "promise_specific_provider", "skip_discovery"],
    },
  },

  {
    id: "pricing_package",
    version: 1,
    level: "DO_IT",
    title: "Pricing & Package Selection",
    description: "Practice selecting the right package and calculating price based on property sqft.",
    role: "sales_rep",
    type: "pricing_package",
    criticality: "critical",
    initial_state: {
      properties: SYNTHETIC_PROPERTIES,
      selected_property_id: null,
      selected_package: null,
      selected_add_ons: [],
      preferred_active: false,
      pricing_result: null,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "property_selection",
        title: "Step 1: Select a Property",
        description: "Select a synthetic property to determine its pricing tier.",
        guidance: "Property sqft determines the pricing tier. Never invent sqft — use the provided data.",
        ui_type: "search_list",
        ui_config: { data_key: "properties", search_placeholder: "Search properties...", display_fields: ["address", "sqft"] },
        expected_action: "select_property",
        expected_category: "property_selection",
        criticality: "high",
      },
      {
        screen: "package_selection",
        title: "Step 2: Select a Package",
        description: "Select the right media package for the prospect's needs.",
        guidance: "The price is determined by the tier + package. Reps must NOT quote custom prices.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true },
        expected_action: "select_package",
        expected_category: "package_selection",
        criticality: "critical",
      },
      {
        screen: "add_ons",
        title: "Step 3: Review Add-Ons (Optional)",
        description: "Review available add-ons and select any that fit the customer's needs.",
        guidance: "Add-ons are optional. Preferred members get 10% off non-MLS packages.",
        ui_type: "form",
        ui_config: { fields: [{ key: "add_ons", label: "Add-Ons", type: "multiselect", options: ADD_ONS.map(a => a.id) }, { key: "preferred_active", label: "Preferred Member", type: "checkbox" }] },
        expected_action: "confirm_pricing",
        expected_category: "pricing_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["select_property", "select_package", "confirm_pricing"],
      critical_failures: ["invent_pricing", "promise_custom_price", "skip_tier_determination"],
    },
  },

  // === SOLVE IT ===
  {
    id: "first_booking",
    version: 1,
    level: "SOLVE_IT",
    title: "First Booking with Objection",
    description: "Handle a price objection during the first booking and guide the customer to the right package.",
    role: "sales_rep",
    type: "first_booking",
    criticality: "high",
    initial_state: {
      customer: { name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142" },
      property: SYNTHETIC_PROPERTIES[0],
      objection: "That's more expensive than the photographer I usually use.",
      selected_package: null,
      objection_handled: false,
      booking_confirmed: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "objection_intro",
        title: "Step 1: Acknowledge the Objection",
        description: "The customer objects to the price. Acknowledge and validate their concern.",
        guidance: "Handle price objections by focusing on value, convenience, and professional presentation — not by discounting.",
        ui_type: "info",
        ui_config: { show_objection: true },
        expected_action: "acknowledge_objection",
        expected_category: "objection_handling",
        criticality: "high",
      },
      {
        screen: "value_response",
        title: "Step 2: Respond with Value",
        description: "Explain the value of professional media vs. a basic photographer.",
        guidance: "Use the value connection: convenience, reliability, professional presentation, reduced coordination.",
        ui_type: "form",
        ui_config: { fields: [{ key: "value_response", label: "Your Value Response", type: "textarea", placeholder: "Explain the value of Arriv's professional media..." }] },
        expected_action: "respond_with_value",
        expected_category: "value_connection",
        criticality: "high",
      },
      {
        screen: "booking_form",
        title: "Step 3: Complete the Booking",
        description: "Guide the customer through the booking form with the right package.",
        guidance: "If a discount is needed, use the manager-approval discount workflow. No discretionary discounts.",
        ui_type: "booking_form",
        ui_config: { show_booking_form: true },
        expected_action: "confirm_booking",
        expected_category: "booking_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["acknowledge_objection", "respond_with_value", "confirm_booking"],
      critical_failures: ["offer_unauthorized_discount", "invent_pricing", "disparage_competitor"],
    },
  },

  {
    id: "post_service_followup",
    version: 1,
    level: "SOLVE_IT",
    title: "Post-Service Follow-Up",
    description: "Handle post-service follow-up and ask for a referral after a completed job.",
    role: "sales_rep",
    type: "post_service_followup",
    criticality: "normal",
    initial_state: {
      customer: { name: "James Wilson", email: "j.wilson@sim.example", phone: "(404) 555-0166", job_completed: true },
      followup_done: false,
      referral_requested: false,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "followup_intro",
        title: "Step 1: Post-Service Follow-Up (within 1 business day)",
        description: "Follow up with the customer within 1 business day of service completion.",
        guidance: "Post-service follow-up within 1 business day is required. Then 7-14 day relationship follow-up.",
        ui_type: "info",
        ui_config: { show_customer: true },
        expected_action: "start_followup",
        expected_category: "followup_initiation",
        criticality: "normal",
      },
      {
        screen: "followup_call",
        title: "Step 2: Check Satisfaction",
        description: "Ask the customer about their satisfaction with the service.",
        guidance: "Check satisfaction, address any concerns, and confirm deliverables were received.",
        ui_type: "form",
        ui_config: { fields: [{ key: "satisfaction_notes", label: "Satisfaction Notes", type: "textarea" }] },
        expected_action: "log_followup",
        expected_category: "followup_completion",
        criticality: "normal",
      },
      {
        screen: "referral_request",
        title: "Step 3: Request a Referral",
        description: "Ask the customer for a referral. Explain the referral program ($20 standard / $40 Preferred).",
        guidance: "Referral program: $20 standard credit, $40 Preferred credit. Never promise cash payouts.",
        ui_type: "form",
        ui_config: { fields: [{ key: "referral_ask", label: "Referral Request", type: "textarea", placeholder: "Ask for a referral..." }] },
        expected_action: "request_referral",
        expected_category: "referral_request",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["start_followup", "log_followup", "request_referral"],
      critical_failures: ["skip_followup", "promise_cash_payout", "promise_provider_details"],
    },
  },

  // === ONBOARD IT ===
  {
    id: "customer_onboarding",
    version: 1,
    level: "ONBOARD_IT",
    title: "Customer Onboarding",
    description: "Guide a new customer through the onboarding process after their first booking.",
    role: "sales_rep",
    type: "customer_onboarding",
    criticality: "normal",
    initial_state: {
      customer: { name: "Sarah Chen", email: "s.chen@sim.example", phone: "(404) 555-0142", booking_confirmed: true },
      onboarding_steps: { welcome_sent: false, account_created: false, preferred_offered: false, first_service_scheduled: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "welcome_intro",
        title: "Step 1: Send Welcome Communication",
        description: "Send a simulated welcome message to the new customer.",
        guidance: "Welcome the customer and confirm their booking details. This is a simulated email — no real email is sent.",
        ui_type: "form",
        ui_config: { fields: [{ key: "welcome_message", label: "Welcome Message", type: "textarea", placeholder: "Welcome to Arriv Estate Media..." }] },
        expected_action: "send_welcome",
        expected_category: "welcome_communication",
        criticality: "normal",
      },
      {
        screen: "account_creation",
        title: "Step 2: Confirm Account Creation",
        description: "Confirm the customer's account has been created in the system.",
        guidance: "Customer conversion: lead → qualified → sale → convert to customer → customer account created → customer can book.",
        ui_type: "info",
        ui_config: { show_account_status: true },
        expected_action: "confirm_account",
        expected_category: "account_confirmation",
        criticality: "normal",
      },
      {
        screen: "preferred_offer",
        title: "Step 3: Offer Preferred Membership",
        description: "Offer the Preferred membership ($29.99/month, 10% discount on services).",
        guidance: "Preferred: $29.99/month, 10% off non-MLS packages, $5 off MLS. Never pressure — inform and offer.",
        ui_type: "boundary",
        ui_config: { show_preferred_offer: true, choices: [{ label: "Offer Preferred (correct)", action: "offer_preferred", correct: true }, { label: "Pressure customer to join", action: "pressure_preferred", correct: false, criticality: "warning" }] },
        expected_action: "offer_preferred",
        expected_category: "preferred_offer",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["send_welcome", "confirm_account", "offer_preferred"],
      critical_failures: ["pressure_preferred", "skip_onboarding", "promise_free_services"],
    },
  },

  {
    id: "customer_account",
    version: 1,
    level: "ONBOARD_IT",
    title: "Customer Account & Deliverables",
    description: "Walk through the customer account view and deliverables access.",
    role: "customer",
    type: "customer_account",
    criticality: "normal",
    initial_state: {
      customer_account: { name: "James Wilson", email: "j.wilson@sim.example", bookings: [{ id: "sim_booking_1", property: "123 Oakwood Dr", package: "Photo + Cinematic", status: "delivered", deliverables_url: "sim://deliverables/1" }], membership: "Preferred" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "customer_dashboard",
        title: "Step 1: View Customer Dashboard",
        description: "See the customer's perspective: their bookings, deliverables, and membership.",
        guidance: "This is the CUSTOMER view. Understand what customers see to better serve them.",
        ui_type: "customer_view",
        ui_config: { show_customer_dashboard: true },
        expected_action: "view_dashboard",
        expected_category: "customer_navigation",
        criticality: "low",
      },
      {
        screen: "deliverables",
        title: "Step 2: Access Deliverables",
        description: "Show how the customer accesses their delivered media.",
        guidance: "Deliverables are shared via a secure link. The customer does NOT see internal provider details.",
        ui_type: "customer_view",
        ui_config: { show_deliverables: true },
        expected_action: "view_deliverables",
        expected_category: "deliverable_access",
        criticality: "normal",
      },
      {
        screen: "membership_view",
        title: "Step 3: View Membership Benefits",
        description: "Review the Preferred membership benefits from the customer perspective.",
        guidance: "Customers see their discount benefits, not internal pricing logic.",
        ui_type: "customer_view",
        ui_config: { show_membership: true },
        expected_action: "view_membership",
        expected_category: "membership_view",
        criticality: "low",
      },
    ],
    validation: {
      required_actions: ["view_dashboard", "view_deliverables", "view_membership"],
      critical_failures: ["expose_provider_payout", "expose_internal_pricing"],
    },
  },

  {
    id: "billing_membership",
    version: 1,
    level: "ONBOARD_IT",
    title: "Billing & Membership Management",
    description: "Handle a billing question and explain membership benefits.",
    role: "sales_rep",
    type: "billing_membership",
    criticality: "normal",
    initial_state: {
      customer: { name: "James Wilson", email: "j.wilson@sim.example", membership: "Preferred", question: "Why was I charged $29.99?" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "billing_question",
        title: "Step 1: Acknowledge the Billing Question",
        description: "The customer asks about a $29.99 charge. Acknowledge and explain.",
        guidance: "The $29.99 is the Preferred monthly membership. Explain the benefits (10% off, $5 off MLS).",
        ui_type: "info",
        ui_config: { show_question: true },
        expected_action: "acknowledge_billing",
        expected_category: "billing_acknowledgment",
        criticality: "normal",
      },
      {
        screen: "explain_benefits",
        title: "Step 2: Explain Membership Benefits",
        description: "Explain the Preferred membership benefits clearly.",
        guidance: "Preferred: $29.99/month, 10% off non-MLS, $5 off MLS. Never promise refunds without manager approval.",
        ui_type: "form",
        ui_config: { fields: [{ key: "benefits_explanation", label: "Benefits Explanation", type: "textarea" }] },
        expected_action: "explain_benefits",
        expected_category: "benefits_explanation",
        criticality: "normal",
      },
      {
        screen: "resolve_question",
        title: "Step 3: Resolve the Question",
        description: "Confirm the customer understands and is satisfied with the explanation.",
        guidance: "If a refund is needed, escalate to manager. No discretionary refunds.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm understanding (correct)", action: "confirm_resolution", correct: true }, { label: "Promise a refund", action: "promise_refund", correct: false, criticality: "critical" }] },
        expected_action: "confirm_resolution",
        expected_category: "question_resolution",
        criticality: "normal",
      },
    ],
    validation: {
      required_actions: ["acknowledge_billing", "explain_benefits", "confirm_resolution"],
      critical_failures: ["promise_refund", "promise_free_services", "disparage_company"],
    },
  },

  // === TEACH IT ===
  {
    id: "customer_teachback",
    version: 1,
    level: "TEACH_IT",
    title: "Customer Teach-Back",
    description: "Explain the Arriv Estate Media service model back as if teaching a new customer.",
    role: "sales_rep",
    type: "customer_teachback",
    criticality: "high",
    initial_state: {
      teachback_responses: { what_we_sell: "", how_pricing_works: "", customer_value: "", media_specialist_role: "" },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "teachback_intro",
        title: "Step 1: Explain What We Sell",
        description: "Explain what Arriv Estate Media sells to a new customer.",
        guidance: "We sell convenience, reliability, professional listing presentation, and reduced coordination.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain what Arriv Estate Media sells:", field_key: "what_we_sell" },
        expected_action: "submit_teachback_1",
        expected_category: "teachback_what_we_sell",
        criticality: "high",
      },
      {
        screen: "teachback_pricing",
        title: "Step 2: Explain How Pricing Works",
        description: "Explain the pricing model (sqft → tier → package → price).",
        guidance: "Pricing is determined by property sqft → tier → package. No invented pricing.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain how pricing works:", field_key: "how_pricing_works" },
        expected_action: "submit_teachback_2",
        expected_category: "teachback_pricing",
        criticality: "high",
      },
      {
        screen: "teachback_media_specialist",
        title: "Step 3: Explain the Media Specialist Role",
        description: "Explain the Media Specialist fulfillment role — without exposing internal payout details.",
        guidance: "Explain that Media Specialists capture and deliver media. Do NOT expose provider payout percentages or internal compensation.",
        ui_type: "teachback",
        ui_config: { prompt: "Explain the Media Specialist role (without exposing internal payout details):", field_key: "media_specialist_role" },
        expected_action: "submit_teachback_3",
        expected_category: "teachback_media_specialist",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["submit_teachback_1", "submit_teachback_2", "submit_teachback_3"],
      critical_failures: ["expose_provider_payout", "invent_pricing", "promise_staging"],
    },
  },

  {
    id: "media_specialist_boundary",
    version: 1,
    level: "TEACH_IT",
    title: "Media Specialist Fulfillment Boundary",
    description: "Understand the Media Specialist lifecycle enough to explain fulfillment — without being trained as a photographer.",
    role: "media_specialist",
    type: "media_specialist_boundary",
    criticality: "critical",
    initial_state: {
      media_specialist: SYNTHETIC_MEDIA_SPECIALIST,
      lifecycle_steps: ["awaiting_capture", "on_site", "captured", "footage_uploaded", "editing", "quality_control", "delivered"],
      current_lifecycle_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "ms_intro",
        title: "Step 1: Understand the Media Specialist Role",
        description: "Learn the Media Specialist fulfillment lifecycle at a high level.",
        guidance: "Reps must understand the lifecycle enough to explain fulfillment, but must NOT be trained as photographers unless separately authorized.",
        ui_type: "media_specialist_view",
        ui_config: { show_role_overview: true },
        expected_action: "review_ms_role",
        expected_category: "role_understanding",
        criticality: "normal",
      },
      {
        screen: "ms_lifecycle",
        title: "Step 2: Walk Through the Fulfillment Lifecycle",
        description: "Walk through each lifecycle step from capture to delivery.",
        guidance: "Lifecycle: awaiting_capture → on_site → captured → footage_uploaded → editing → quality_control → delivered.",
        ui_type: "lifecycle",
        ui_config: { steps_key: "lifecycle_steps" },
        expected_action: "walk_lifecycle",
        expected_category: "lifecycle_understanding",
        criticality: "normal",
      },
      {
        screen: "boundary_check",
        title: "Step 3: Boundary Check",
        description: "Confirm you understand what a rep may and may not promise about Media Specialist fulfillment.",
        guidance: "Reps may explain the fulfillment process. Reps may NOT promise specific providers, payout details, or unauthorized turnaround guarantees.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Explain fulfillment process (correct)", action: "explain_fulfillment", correct: true }, { label: "Promise a specific photographer", action: "promise_provider", correct: false, criticality: "critical" }, { label: "Share provider payout %", action: "expose_payout", correct: false, criticality: "critical" }] },
        expected_action: "explain_fulfillment",
        expected_category: "boundary_understanding",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["review_ms_role", "walk_lifecycle", "explain_fulfillment"],
      critical_failures: ["promise_provider", "expose_payout", "promise_turnaround_guarantee"],
    },
  },

  // === PROVE IT ===
  {
    id: "project_lifecycle",
    version: 1,
    level: "PROVE_IT",
    title: "Project Lifecycle Management",
    description: "Manage a simulated project from booking through delivery, demonstrating full lifecycle understanding.",
    role: "sales_rep",
    type: "project_lifecycle",
    criticality: "high",
    initial_state: {
      project: { id: "sim_project_1", customer: "Sarah Chen", property: "123 Oakwood Dr NE, Atlanta, GA 30305", package: "photo_cinematic", status: "booked" },
      lifecycle: ["booked", "media_partner_assigned", "capture_scheduled", "captured", "footage_uploaded", "editing", "quality_control", "delivered"],
      current_step: 0,
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "project_overview",
        title: "Step 1: Review the Project",
        description: "Review the simulated project details and lifecycle stages.",
        guidance: "Understand the full project lifecycle from booking to delivery.",
        ui_type: "info",
        ui_config: { show_project: true },
        expected_action: "review_project",
        expected_category: "project_review",
        criticality: "normal",
      },
      {
        screen: "advance_lifecycle",
        title: "Step 2: Advance Through Lifecycle Stages",
        description: "Advance the project through each lifecycle stage.",
        guidance: "Each stage has dependencies. Don't skip stages. Footage must be uploaded before editing.",
        ui_type: "lifecycle",
        ui_config: { steps_key: "lifecycle", current_step_key: "current_step" },
        expected_action: "advance_lifecycle",
        expected_category: "lifecycle_advancement",
        criticality: "high",
      },
      {
        screen: "delivery_confirmation",
        title: "Step 3: Confirm Delivery",
        description: "Confirm the deliverables have been sent to the customer.",
        guidance: "Delivery is the final stage. Confirm the customer received their media. Do NOT upload real deliverables in simulation.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm simulated delivery", action: "confirm_delivery", correct: true }, { label: "Upload a real file", action: "upload_real_file", correct: false, criticality: "critical" }] },
        expected_action: "confirm_delivery",
        expected_category: "delivery_confirmation",
        criticality: "high",
      },
    ],
    validation: {
      required_actions: ["review_project", "advance_lifecycle", "confirm_delivery"],
      critical_failures: ["upload_real_file", "skip_lifecycle_stage", "charge_real_stripe"],
    },
  },

  {
    id: "final_certification",
    version: 1,
    level: "PROVE_IT",
    title: "Final Certification Scenario",
    description: "Demonstrate mastery across the full sales process in a final certification scenario.",
    role: "sales_rep",
    type: "final_certification",
    criticality: "critical",
    initial_state: {
      prospect: SYNTHETIC_PROSPECTS[1],
      property: SYNTHETIC_PROPERTIES[1],
      certification_steps: { research: false, video_check: false, discovery: false, pricing: false, booking: false, followup: false },
      step_index: 0,
      completed: false,
    },
    steps: [
      {
        screen: "cert_intro",
        title: "Step 1: Research the Prospect",
        description: "Start the certification by researching the prospect and performing the professional video check.",
        guidance: "This is the PROVE IT level. Demonstrate the full process without guidance.",
        ui_type: "video_check",
        ui_config: { prospect_key: "prospect" },
        expected_action: "cert_research",
        expected_category: "certification_research",
        criticality: "critical",
      },
      {
        screen: "cert_discovery_pricing",
        title: "Step 2: Discovery & Pricing",
        description: "Complete discovery and calculate the correct pricing for the property.",
        guidance: "Use the correct tier and package. No invented pricing.",
        ui_type: "pricing",
        ui_config: { show_pricing_calculator: true, property_key: "property" },
        expected_action: "cert_pricing",
        expected_category: "certification_pricing",
        criticality: "critical",
      },
      {
        screen: "cert_boundary",
        title: "Step 3: Boundary Certification",
        description: "Confirm you understand all critical boundaries.",
        guidance: "Final boundary check: no invented pricing, no unauthorized discounts, no provider payout exposure, no staging promises.",
        ui_type: "boundary",
        ui_config: { choices: [{ label: "Confirm all boundaries understood", action: "cert_confirm_boundaries", correct: true }, { label: "I'll offer custom discounts", action: "cert_custom_discount", correct: false, criticality: "critical" }, { label: "I'll share provider payouts", action: "cert_expose_payout", correct: false, criticality: "critical" }] },
        expected_action: "cert_confirm_boundaries",
        expected_category: "certification_boundary",
        criticality: "critical",
      },
    ],
    validation: {
      required_actions: ["cert_research", "cert_pricing", "cert_confirm_boundaries"],
      critical_failures: ["cert_custom_discount", "cert_expose_payout", "invent_pricing", "promise_staging", "upload_real_file", "charge_real_stripe"],
    },
  },
];

export function getScenariosByLevel(level) {
  return SCENARIOS.filter(s => s.level === level);
}

export function getScenarioById(id) {
  return SCENARIOS.find(s => s.id === id);
}