import { createClientFromRequest } from 'npm:@base44/sdk@0.8.21';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Fetch all activity logs in batches
    const all = await base44.asServiceRole.entities.ActivityLog.list('-activity_date', 1000);

    // Find all records that have a call map embedded in their notes
    const withCallMaps = all.filter(a => {
      const notes = a.notes || '';
      return /--- CALL MAP ---/i.test(notes);
    });

    if (withCallMaps.length === 0) {
      return Response.json({ success: true, processed: 0, message: 'No call maps found to learn from' });
    }

    // Extract all call map content
    const callMaps = withCallMaps.map(a => {
      const notes = a.notes || '';
      const mapMatch = notes.match(/--- CALL MAP ---\s*([\s\S]*)/i);
      return {
        id: a.id,
        contact_name: a.contact_name,
        sales_member_id: a.sales_member_id,
        sales_member_email: a.sales_member_email,
        callMap: mapMatch ? mapMatch[1].trim() : ''
      };
    }).filter(x => x.callMap.length > 50);

    if (callMaps.length === 0) {
      return Response.json({ success: true, processed: 0, message: 'No usable call map content found' });
    }

    // Combine all call maps into one big analysis prompt to extract system-wide patterns
    const sampleMaps = callMaps.slice(0, 20); // Take up to 20 for analysis
    const combinedSample = sampleMaps
      .map((c, i) => `=== CALL MAP ${i + 1} (${c.contact_name || 'Unknown'}) ===\n${c.callMap.slice(0, 800)}`)
      .join('\n\n');

    const analysisRes = await base44.asServiceRole.integrations.Core.InvokeLLM({
      prompt: `You are analyzing ${sampleMaps.length} real-world sales call maps that were used and/or manually refined by sales reps at ARRIV, a real estate photography & video company.

Your job: Extract recurring style patterns, language preferences, and structural insights that should be applied to ALL future call maps generated by the AI.

CALL MAPS TO ANALYZE:
${combinedSample}

Based on ALL of the above call maps, extract:
1. Tone and language patterns that appear most effective (casual, direct, specific?)
2. Structural patterns (what sections work best, what order?)
3. Specific phrases or vocabulary that appears frequently and should be reused
4. Objection handling approaches that appear most refined
5. Opening line patterns that seem most natural and human
6. Anything that was clearly hand-crafted vs AI-generic (prefer the hand-crafted style)

Format as a clear bullet-point list of 8-12 actionable style rules the AI should follow when writing call maps. Be specific — quote actual phrases when useful. These will be injected directly into the AI prompt as instructions.`,
      model: 'claude_sonnet_4_6'
    });

    const learnedInsights = typeof analysisRes === 'string' ? analysisRes : JSON.stringify(analysisRes);

    // Find existing system-wide profile (sales_member_id = 'system') or create one
    const existingProfiles = await base44.asServiceRole.entities.SalesRepStyleProfile.filter({ sales_member_id: 'system' });
    const existingProfile = existingProfiles?.[0];

    const timestamp = new Date().toISOString().slice(0, 10);
    const newEntry = `[Backfilled ${timestamp} from ${callMaps.length} saved call maps]\n${learnedInsights}`;

    if (existingProfile) {
      await base44.asServiceRole.entities.SalesRepStyleProfile.update(existingProfile.id, {
        learned_preferences: newEntry,
        edit_count: callMaps.length,
        last_updated: new Date().toISOString()
      });
    } else {
      await base44.asServiceRole.entities.SalesRepStyleProfile.create({
        sales_member_id: 'system',
        sales_member_email: 'system',
        learned_preferences: newEntry,
        edit_count: callMaps.length,
        last_updated: new Date().toISOString()
      });
    }

    // Also run per-rep learning for reps who have edited call maps
    const byRep = {};
    callMaps.forEach(c => {
      const key = c.sales_member_id || c.sales_member_email || 'unknown';
      if (!byRep[key]) byRep[key] = { id: c.sales_member_id, email: c.sales_member_email, maps: [] };
      byRep[key].maps.push(c);
    });

    const repEntries = Object.values(byRep).filter(r => r.id && r.id !== 'unknown' && r.maps.length >= 2);
    await Promise.all(repEntries.map(async (rep) => {
      const repSample = rep.maps.slice(0, 10).map((c, i) => `=== MAP ${i+1} ===\n${c.callMap.slice(0, 600)}`).join('\n\n');
      const repAnalysis = await base44.asServiceRole.integrations.Core.InvokeLLM({
        prompt: `Analyze these ${rep.maps.length} call maps from a single sales rep and extract their personal communication style preferences as 5-8 bullet points:\n\n${repSample}`,
        model: 'gpt_5_mini'
      });
      const repInsights = typeof repAnalysis === 'string' ? repAnalysis : JSON.stringify(repAnalysis);
      const repProfiles = await base44.asServiceRole.entities.SalesRepStyleProfile.filter({ sales_member_id: rep.id });
      const repProfile = repProfiles?.[0];
      const repEntry = `[Backfilled ${timestamp} from ${rep.maps.length} call maps]\n${repInsights}`;
      if (repProfile) {
        await base44.asServiceRole.entities.SalesRepStyleProfile.update(repProfile.id, {
          learned_preferences: repEntry,
          edit_count: rep.maps.length,
          last_updated: new Date().toISOString()
        });
      } else {
        await base44.asServiceRole.entities.SalesRepStyleProfile.create({
          sales_member_id: rep.id,
          sales_member_email: rep.email,
          learned_preferences: repEntry,
          edit_count: rep.maps.length,
          last_updated: new Date().toISOString()
        });
      }
    }));

    return Response.json({
      success: true,
      processed: callMaps.length,
      repsLearned: repEntries.length,
      systemProfileUpdated: true,
      message: `Learned from ${callMaps.length} existing call maps across ${repEntries.length} reps`
    });

  } catch (error) {
    console.error('[backfillStyleLearning] Error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});