// Canonical Arriv Studio library defaults.
// These mirror the canonical Studio library catalog. When ARRIV_STUDIO_BASE_URL
// is configured, syncStudioLibraries pulls live data from Studio and overwrites
// these records. Until then, these serve as the canonical source of truth.

export const CANONICAL_PRESENTERS = [
  {
    studio_id: "presenter_erica",
    name: "Erica",
    source: "ARRIV_AI",
    status: "available",
    category: "ARRIV AI",
    description: "Warm, professional, authoritative",
    tags: ["front", "left three quarter", "right three quarter", "medium"],
  },
  {
    studio_id: "presenter_daniel",
    name: "Daniel",
    source: "ARRIV_AI",
    status: "available",
    category: "ARRIV AI",
    description: "Calm, measured, trustworthy",
    tags: ["front", "left three quarter", "medium"],
  },
  {
    studio_id: "presenter_maya",
    name: "Maya",
    source: "ARRIV_AI",
    status: "available",
    category: "ARRIV AI",
    description: "Bright, energetic, friendly",
    tags: ["front", "right three quarter", "wide"],
  },
  {
    studio_id: "presenter_james_holloway",
    name: "James Holloway",
    source: "ARRIV_PREFERRED",
    status: "available",
    category: "HUMAN",
    description: "Polished, corporate, confident",
    tags: ["front", "left three quarter", "right three quarter", "left side", "right side", "medium", "wide"],
  },
  {
    studio_id: "presenter_priya_sharma",
    name: "Priya Sharma",
    source: "ARRIV_PREFERRED",
    status: "limited",
    category: "HUMAN",
    description: "Approachable, articulate, warm",
    tags: ["front", "left three quarter", "right three quarter", "medium"],
  },
];

export const CANONICAL_VOICES = [
  {
    studio_id: "voice_aria_warm",
    name: "Aria (Warm)",
    source: "ARRIV",
    category: "FEMALE",
    description: "Warm, conversational",
    metadata: { language: "en-US" },
  },
  {
    studio_id: "voice_marcus_authoritative",
    name: "Marcus (Authoritative)",
    source: "ARRIV",
    category: "MALE",
    description: "Authoritative, clear",
    metadata: { language: "en-US" },
  },
  {
    studio_id: "voice_sophie_bright",
    name: "Sophie (Bright)",
    source: "ELEVENLABS",
    category: "FEMALE",
    description: "Bright, energetic",
    metadata: { language: "en-GB" },
  },
  {
    studio_id: "voice_james_calm",
    name: "James (Calm)",
    source: "HEYGEN",
    category: "MALE",
    description: "Calm, measured",
    metadata: { language: "en-US" },
  },
  {
    studio_id: "voice_lena_friendly",
    name: "Lena (Friendly)",
    source: "ELEVENLABS",
    category: "FEMALE",
    description: "Friendly, approachable",
    metadata: { language: "en-AU" },
  },
];

export const CANONICAL_MUSIC = [
  {
    studio_id: "music_corporate_confidence",
    name: "Corporate Confidence",
    source: "ARRIV",
    category: "CORPORATE",
    description: "Training intros, product walkthroughs, business explainers",
    metadata: { energy: "medium", mood: "Uplifting", bpm: 110, duration_sec: 120, recommended_use: "Training intros, product walkthroughs, business explainers" },
  },
  {
    studio_id: "music_cinematic_horizon",
    name: "Cinematic Horizon",
    source: "ARRIV",
    category: "CINEMATIC",
    description: "Brand films, high-impact openers, emotional storytelling",
    metadata: { energy: "high", mood: "Epic", bpm: 90, duration_sec: 150, recommended_use: "Brand films, high-impact openers, emotional storytelling" },
  },
  {
    studio_id: "music_soft_reflection",
    name: "Soft Reflection",
    source: "ARRIV",
    category: "AMBIENT",
    description: "Voiceover beds, thoughtful narration, healthcare",
    metadata: { energy: "low", mood: "Calm", bpm: 70, duration_sec: 180, recommended_use: "Voiceover beds, thoughtful narration, healthcare" },
  },
  {
    studio_id: "music_upbeat_energy",
    name: "Upbeat Energy",
    source: "ARRIV",
    category: "POP",
    description: "Social ads, product launches, lifestyle content",
    metadata: { energy: "high", mood: "Happy", bpm: 128, duration_sec: 90, recommended_use: "Social ads, product launches, lifestyle content" },
  },
  {
    studio_id: "music_tech_forward",
    name: "Tech Forward",
    source: "ARRIV",
    category: "ELECTRONIC",
    description: "SaaS demos, tech product, onboarding",
    metadata: { energy: "medium", mood: "Driven", bpm: 120, duration_sec: 110, recommended_use: "SaaS demos, tech product, onboarding" },
  },
  {
    studio_id: "music_warm_story",
    name: "Warm Story",
    source: "ARRIV",
    category: "ACOUSTIC",
    description: "Testimonials, nonprofit, human-interest stories",
    metadata: { energy: "low", mood: "Heartwarming", bpm: 85, duration_sec: 140, recommended_use: "Testimonials, nonprofit, human-interest stories" },
  },
  {
    studio_id: "music_social_pulse",
    name: "Social Pulse",
    source: "ARRIV",
    category: "ELECTRONIC",
    description: "Short-form social, reels, TikTok cutdowns",
    metadata: { energy: "high", mood: "Energetic", bpm: 140, duration_sec: 60, recommended_use: "Short-form social, reels, TikTok cutdowns" },
  },
  {
    studio_id: "music_training_focus",
    name: "Training Focus",
    source: "ARRIV",
    category: "CORPORATE",
    description: "Long-form training, education, tutorials",
    metadata: { energy: "medium", mood: "Neutral", bpm: 100, duration_sec: 130, recommended_use: "Long-form training, education, tutorials" },
  },
  {
    studio_id: "music_inspiring_rise",
    name: "Inspiring Rise",
    source: "ARRIV",
    category: "ORCHESTRAL",
    description: "Motivational, recruitment, brand anthems",
    metadata: { energy: "high", mood: "Motivational", bpm: 95, duration_sec: 160, recommended_use: "Motivational, recruitment, brand anthems" },
  },
  {
    studio_id: "music_forward_motion",
    name: "Forward Motion",
    source: "ARRIV",
    category: "CORPORATE",
    description: "",
    metadata: { energy: "medium" },
  },
  {
    studio_id: "music_coral_sunrise",
    name: "Coral Sunrise",
    source: "ARRIV",
    category: "AMBIENT",
    description: "",
    metadata: { energy: "low" },
  },
  {
    studio_id: "music_pulse_drive",
    name: "Pulse Drive",
    source: "ARRIV",
    category: "ELECTRONIC",
    description: "",
    metadata: { energy: "high" },
  },
];

export const ALL_CANONICAL = [
  ...CANONICAL_PRESENTERS.map((p) => ({ ...p, asset_type: "presenter" })),
  ...CANONICAL_VOICES.map((v) => ({ ...v, asset_type: "voice" })),
  ...CANONICAL_MUSIC.map((m) => ({ ...m, asset_type: "music" })),
];